baños: "2";
caracteristica_garage: true;
caracteristica_pet: true;
caracteristica_piscina: true;
caracteristica_terraza: true;
comunidad: "Aragón";
habitaciones: "2";
operacion: "alquiler";
preciomax: "5000";
preciomin: "4000";
provincia: "Huesca";
vivienda_chalet: true;
vivienda_piso: true;
vivienda_villa: true;

[
  {
    aseos: 2,
    comunidad: "andalucia",
    direccion: "hortaleza 23",
    garage: false,
    habitaciones: 4,
    id: 3,
    municipio: "ensanche",
    pet: true,
    piscina: false,
    precio: 1500,
    provincia: "granada",
    terraza: true,
    tipo_operacion: "alquiler",
    tipo_vivienda: "chalet",
  },
  {
    "ba\u00f1os": 1,
    comunidad: "catalu\u00f1a",
    direccion: "matamulas 12",
    garage: true,
    habitaciones: 3,
    id: 4,
    municipio: "almudena",
    pet: false,
    piscina: true,
    precio: 2400,
    provincia: "gerona",
    terraza: false,
    tipo_operacion: "alquiler",
    tipo_vivienda: "piso",
  },
  {
    "ba\u00f1os": 3,
    comunidad: "comunidad valenciana",
    direccion: "calle de las misiones cartesianas 6",
    garage: true,
    habitaciones: 6,
    id: 5,
    municipio: "novelda",
    pet: true,
    piscina: true,
    precio: 3450,
    provincia: "alicante",
    terraza: true,
    tipo_operacion: "compra",
    tipo_vivienda: "villa",
  },
  {
    "ba\u00f1os": 1,
    comunidad: "pais vasco",
    direccion: "las lechuzas 4",
    garage: true,
    habitaciones: 2,
    id: 6,
    municipio: "ranagordarraga",
    pet: false,
    piscina: false,
    precio: 900,
    provincia: "vizcaya",
    terraza: true,
    tipo_operacion: "compra",
    tipo_vivienda: "chalet",
  },
];


{
  id: 1,
  tipo_operacion: "alquiler",
  comunidad: "Madrid",
  provincia: "Madrid",
  municipio: "Madrid",
  direccion: "Las Moras 1",
  precio: "800",
  tipo_vivienda: "Piso",
  habitaciones: "2",
  baños: "1",
  pet: true,
  piscina: true,
  terraza: false,
  garage: false,
  descripcion: "hermoso predio con sol todo el año",
  main_image:
    "https://media-cdn.tripadvisor.com/media/vr-splice-j/05/dc/2c/dd.jpg",
},
{
  id: 2,
  tipo_operacion: "alquiler",
  comunidad: "Madrid",
  provincia: "Madrid",
  municipio: "Madrid",
  direccion: "Las Moras 2",
  precio: "1500",
  tipo_vivienda: "Chalet",
  habitaciones: "1",
  baños: "2",
  pet: false,
  piscina: true,
  terraza: false,
  garage: true,
  descripcion: "lujoso condominio para veranear",
  main_image:
    "https://media.vrbo.com/lodging/22000000/21730000/21726900/21726891/796ac4ff.f6.jpg",
},
{
  id: 3,
  tipo_operacion: "alquiler",
  comunidad: "Madrid",
  provincia: "Madrid",
  municipio: "Madrid",
  direccion: "Las Moras 3",
  precio: "3500",
  tipo_vivienda: "Piso",
  habitaciones: "4",
  baños: "3",
  pet: true,
  piscina: false,
  terraza: false,
  garage: false,
  descripcion: "relájese en este lujoso piso en las montañas",
  main_image:
    "https://media-cdn.tripadvisor.com/media/photo-s/07/ef/9e/b8/casa-bonita-hotel-boutique.jpg",
},
{
  id: 4,
  tipo_operacion: "compra",
  comunidad: "Madrid",
  provincia: "Madrid",
  municipio: "Madrid",
  direccion: "Las Moras 4",
  precio: "150000",
  tipo_vivienda: "Chalet",
  habitaciones: "3",
  baños: "2",
  pet: false,
  piscina: true,
  terraza: true,
  garage: true,
  descripcion: "disfrute de una escapada de lujo",
  main_image:
    "https://ak-d.tripcdn.com/images/22071e000001gamro1BDC_Z_1100_824_R5_Q70_D.jpg",
},
{
  id: 5,
  tipo_operacion: "compra",
  comunidad: "Madrid",
  provincia: "Madrid",
  municipio: "Madrid",
  direccion: "Las Moras 5",
  precio: "690000",
  tipo_vivienda: "Piso",
  habitaciones: "1",
  baños: "4",
  pet: true,
  piscina: true,
  terraza: true,
  garage: true,
  descripcion: "cozy apartment with ocean view",
  main_image:
    "https://www.isoladiminorca.com/wp-content/uploads/2021/06/0.-Casa-Bonita-Menorca-784x400.jpg",
},