"""Reviews model

Revision ID: 00ea2238d82f
Revises: d3346aea46d8
Create Date: 2023-08-07 23:40:57.705309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea2238d82f'
down_revision = 'd3346aea46d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(length=450), nullable=True),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('car_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['car_name'], ['car.car_name'], ),
    sa.ForeignKeyConstraint(['user_first_name'], ['user.first_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('overall_rating')

    op.drop_table('review')
    # ### end Alembic commands ###
