const Constants= Object.freeze({

  MOUSE_BTN_LEFT: 0,
  MOUSE_BTN_MIDDLE: 1,
  MOUSE_BTN_RIGHT: 2,

  COOKIE_SAMESITE_NONE: "None",
  COOKIE_SAMESITE_NONE_SECURE: "None; Secure",
  COOKIE_SAMESITE_LAX: "Lax",
  COOKIE_SAMESITE_STRICT: "Strict",

  SESSION_MODE_SIGNUP: 0,
  SESSION_MODE_LOGIN: 1,
  SESSION_MODE_LOGOUT: 2,
  SESSION_MODE_RECOVER: 3,
  SESSION_MODE_DELETED: 4,

  USERPREFS_DARKMODE: "darkMode",

  DEVPREFS_SHOWSTATE: "showState",
  DEVPREFS_PANELPOSITION: "panelPosition",
  DEVPREFS_DEVRENDER: "devRender",

  BOARD_SIZE_PIXELS: 1048576,

  BOARD_ITEMTYPE_LIST: 0,
  BOARD_ITEMTYPE_LABEL: 1
})

export default Constants