"""empty message

Revision ID: 0006e5e67d97
Revises: 42a7b0ddf922
Create Date: 2024-02-29 18:00:26.301384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006e5e67d97'
down_revision = '42a7b0ddf922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###
