"""empty message

Revision ID: 01fa2e18d207
Revises: c21f549b1fcf
Create Date: 2024-05-11 20:56:08.833804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fa2e18d207'
down_revision = 'c21f549b1fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('room_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key('room_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
