"""empty message

Revision ID: 020abc4bc22e
Revises: 98ffb9994c8a
Create Date: 2024-05-24 01:58:42.013637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020abc4bc22e'
down_revision = '98ffb9994c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
