"""empty message

Revision ID: 0869fdfc819c
Revises: 
Create Date: 2023-12-12 21:16:41.879061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0869fdfc819c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True, foreign_key=True),
    sa.Column('apellido', sa.String(length=200), nullable=False, foreign_key=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False, foreign_key=True),
    sa.Column('fecha', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.drop_table('prestador_publicacion')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoUsuario', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipoUsuario', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.drop_column('tipoUsuario')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tipoUsuario')

    op.create_table('prestador_publicacion',
    sa.Column('idPrestadorPublicacion', sa.INTEGER(), server_default=sa.text('nextval(\'"prestador_publicacion_idPrestadorPublicacion_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['user.idUser'], name='prestador_publicacion_idUser_fkey'),
    sa.PrimaryKeyConstraint('idPrestadorPublicacion', name='prestador_publicacion_pkey')
    )
    op.drop_table('user_publicacion')
    # ### end Alembic commands ###
