"""empty message

Revision ID: 09dbb8d870c7
Revises: 122d7c689bcc
Create Date: 2022-08-30 16:58:56.948760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dbb8d870c7'
down_revision = '122d7c689bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmueble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.String(length=80), nullable=False),
    sa.Column('comunidad', sa.String(length=80), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.Column('municipio', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('tipo_vivienda', sa.String(length=80), nullable=False),
    sa.Column('habitaciones', sa.Integer(), nullable=False),
    sa.Column('baños', sa.Integer(), nullable=False),
    sa.Column('pet', sa.Boolean(), nullable=False),
    sa.Column('piscina', sa.Boolean(), nullable=False),
    sa.Column('terraza', sa.Boolean(), nullable=False),
    sa.Column('garage', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.String(length=80), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('inmueble_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'inmueble', ['inmueble_id'], ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'inmueble_id')
    op.drop_table('imagen')
    op.drop_table('inmueble')
    # ### end Alembic commands ###
