"""empty message

Revision ID: 0c5ad9609f90
Revises: 6681aeef3304
Create Date: 2021-03-24 19:27:46.153193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c5ad9609f90'
down_revision = '6681aeef3304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicio_registrados', 'id_servicios_prestados',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicios_prestados', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('servicios_prestados', 'fecha_termino',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('servicios_prestados', 'id_users_compra',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicios_prestados', 'id_users_compra',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicios_prestados', 'fecha_termino',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('servicios_prestados', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('servicio_registrados', 'id_servicios_prestados',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
