"""empty message

Revision ID: 0c7edef0ba0c
Revises: 903c3ac832c7
Create Date: 2024-05-20 20:41:45.743437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7edef0ba0c'
down_revision = '903c3ac832c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('text_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
