"""empty message

Revision ID: 105e1e273ff9
Revises: f1a4c935a120
Create Date: 2024-05-15 00:40:33.113591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105e1e273ff9'
down_revision = 'f1a4c935a120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('certificate_teacher',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('certificate_teacher',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
