"""empty message

Revision ID: 10b9a040eb47
Revises: 940f3ba18bf1
Create Date: 2024-02-24 01:10:44.273241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9a040eb47'
down_revision = '940f3ba18bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=8), nullable=False))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('dni')

    # ### end Alembic commands ###
