"""empty message

Revision ID: 10c8563ad352
Revises: 014ded544b12
Create Date: 2021-03-12 07:04:31.472874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c8563ad352'
down_revision = '014ded544b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('cocktail_name', sa.String(length=250), nullable=False))
    op.alter_column('favorite', 'cocktail_img',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('favorite', 'cockatail_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('cockatail_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.alter_column('favorite', 'cocktail_img',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('favorite', 'cocktail_name')
    # ### end Alembic commands ###
