"""empty message

Revision ID: 1184565da004
Revises: cd7211caf692
Create Date: 2023-07-26 18:25:21.661202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1184565da004'
down_revision = 'cd7211caf692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Favorites_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['Favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    op.drop_table('destinations')
    # ### end Alembic commands ###
