"""empty message

Revision ID: 1303352f2389
Revises: 9588601c10da
Create Date: 2023-03-24 00:32:43.619648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1303352f2389'
down_revision = '9588601c10da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_type', sa.String(length=120), nullable=False),
    sa.Column('plant_size', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_number', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plant_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('plant_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('customer_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.drop_table('order')
    # ### end Alembic commands ###
