"""empty message

Revision ID: 139128152135
Revises: 01fa2e18d207
Create Date: 2024-05-11 21:54:03.227758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139128152135'
down_revision = '01fa2e18d207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
