"""null ok

Revision ID: 16038e2c8ff0
Revises: 67002fe31045
Create Date: 2023-11-24 18:59:45.488701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16038e2c8ff0'
down_revision = '67002fe31045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('rubro',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('fecha_de_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rubro',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('fecha_de_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
