"""empty message

Revision ID: 1aaf67d6917e
Revises: 2bd4047cb5f4
Create Date: 2024-08-13 00:56:50.848857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaf67d6917e'
down_revision = '2bd4047cb5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_game_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_game_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_favorite_game_id_fkey', 'game', ['favorite_game_id'], ['id'])

    op.drop_table('favorite')
    # ### end Alembic commands ###
