"""empty message

Revision ID: 1bc188b0a759
Revises: 33c3b8488bf7
Create Date: 2023-07-14 02:55:18.037496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc188b0a759'
down_revision = '33c3b8488bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved', schema=None) as batch_op:
        batch_op.drop_constraint('saved_car_id_key', type_='unique')
        batch_op.drop_constraint('saved_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved', schema=None) as batch_op:
        batch_op.create_unique_constraint('saved_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('saved_car_id_key', ['car_id'])

    # ### end Alembic commands ###
