"""empty message

Revision ID: 1c3dcdab3a14
Revises: 084ad44f4e08
Create Date: 2021-03-18 16:22:40.535483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3dcdab3a14'
down_revision = '084ad44f4e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('cocktail_id', sa.Integer(), nullable=False))
    op.alter_column('favorite', 'cocktail_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.create_unique_constraint(None, 'favorite', ['cocktail_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='unique')
    op.alter_column('favorite', 'cocktail_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('favorite', 'cocktail_id')
    # ### end Alembic commands ###
