"""empty message

Revision ID: 1c760ed5f7bb
Revises: b6fa5bf64dcc
Create Date: 2024-05-25 02:26:28.401923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c760ed5f7bb'
down_revision = 'b6fa5bf64dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
