"""empty message

Revision ID: 233f477360f4
Revises: 13a076ce33d2
Create Date: 2021-05-13 16:53:30.451611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233f477360f4'
down_revision = '13a076ce33d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_product_name_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_product_name_key', 'product', ['product_name'])
    # ### end Alembic commands ###
