"""empty message

Revision ID: 249a1d325e24
Revises: 28e761fa64d9
Create Date: 2023-08-09 18:48:17.596793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249a1d325e24'
down_revision = '28e761fa64d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###
