"""empty message

Revision ID: 254de1ea23d5
Revises: 44b6c0363a6f
Create Date: 2023-12-11 12:52:30.123358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254de1ea23d5'
down_revision = '44b6c0363a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_publicacion',
    sa.Column('idPublicacion', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('comuna', sa.String(length=200), nullable=False),
    sa.Column('rubro', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPublicacion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fecha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_publicacion')
    # ### end Alembic commands ###
