"""empty message

Revision ID: 265ad9a4ffbe
Revises: e651760166b6
Create Date: 2024-08-28 15:30:21.989976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265ad9a4ffbe'
down_revision = 'e651760166b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.String(length=120), nullable=True))
        batch_op.drop_column('niveles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveles', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('nivel')

    # ### end Alembic commands ###
