"""empty message

Revision ID: 2763ad07d870
Revises: 1303352f2389
Create Date: 2023-04-02 01:58:41.108332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2763ad07d870'
down_revision = '1303352f2389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoe', schema=None) as batch_op:
        batch_op.drop_constraint('shoe_photo_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoe', schema=None) as batch_op:
        batch_op.create_unique_constraint('shoe_photo_key', ['photo'])

    # ### end Alembic commands ###
