"""empty message

Revision ID: 290a0b0e7350
Revises: 1aa46aef58ab
Create Date: 2023-05-02 19:44:44.783112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290a0b0e7350'
down_revision = '1aa46aef58ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_owner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('technician_user_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_owner'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('technician_user_key', ['user'])
        batch_op.drop_column('user_owner')

    # ### end Alembic commands ###
