"""empty message

Revision ID: 2a0dee1e0fbb
Revises: 224b5c35979a
Create Date: 2024-05-11 01:08:20.604357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0dee1e0fbb'
down_revision = '224b5c35979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_membership_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_membership_history', ['active_membership_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active_membership_id')

    # ### end Alembic commands ###
