"""empty message

Revision ID: 2a40891a838f
Revises: 78fef76986e6
Create Date: 2021-04-27 16:41:52.899469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a40891a838f'
down_revision = '78fef76986e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coupons', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'coupons', 'supermarket', ['market_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    # ### end Alembic commands ###
