"""empty message

Revision ID: 2b30d730877f
Revises: 0e83ec9c47a6
Create Date: 2023-04-18 19:20:47.305778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b30d730877f'
down_revision = '0e83ec9c47a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['roles_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roles_id')

    # ### end Alembic commands ###
