"""empty message

Revision ID: 2bb7f04a1468
Revises: c04e36bebd3d
Create Date: 2023-07-11 09:28:10.216066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb7f04a1468'
down_revision = 'c04e36bebd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_column('mail')

    # ### end Alembic commands ###
