"""empty message

Revision ID: 2f11de132ef3
Revises: 
Create Date: 2022-09-14 01:21:22.432309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f11de132ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dulce',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('ingredientes', sa.String(length=1000), nullable=False),
    sa.Column('tiempo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('platos',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('ingredientes', sa.String(length=1000), nullable=False),
    sa.Column('tiempo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veget',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('ingredientes', sa.String(length=1000), nullable=False),
    sa.Column('tiempo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favPlatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('platos_uid', sa.Integer(), nullable=True),
    sa.Column('dulce_uid', sa.Integer(), nullable=True),
    sa.Column('veget_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dulce_uid'], ['dulce.uid'], ),
    sa.ForeignKeyConstraint(['platos_uid'], ['platos.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.email'], ),
    sa.ForeignKeyConstraint(['veget_uid'], ['veget.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favPlatos')
    op.drop_table('veget')
    op.drop_table('user')
    op.drop_table('platos')
    op.drop_table('dulce')
    # ### end Alembic commands ###
