"""empty message

Revision ID: 32426e570c6a
Revises: fc7a8d22b334
Create Date: 2024-02-17 16:05:00.885196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32426e570c6a'
down_revision = 'fc7a8d22b334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=False),
    sa.Column('asana_focus', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asana_focus'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('duration'),
    sa.UniqueConstraint('level'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
