"""empty message

<<<<<<<< HEAD:migrations/versions/35137d7db7b8_.py
Revision ID: 35137d7db7b8
Revises: 
Create Date: 2023-06-06 23:19:16.321870
========
Revision ID: bc8b7507631f
Revises: 
Create Date: 2023-06-08 00:22:56.040059
>>>>>>>> af9ef768e7718c6062d8592fdc2bd9baa6de8554:migrations/versions/bc8b7507631f_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/35137d7db7b8_.py
revision = '35137d7db7b8'
========
revision = 'bc8b7507631f'
>>>>>>>> af9ef768e7718c6062d8592fdc2bd9baa6de8554:migrations/versions/bc8b7507631f_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('address_one', sa.String(length=50), nullable=False),
    sa.Column('address_two', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
<<<<<<<< HEAD:migrations/versions/35137d7db7b8_.py
    op.create_table('services_sedan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_service', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_service'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services_suv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_service', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_service'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
========
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
>>>>>>>> af9ef768e7718c6062d8592fdc2bd9baa6de8554:migrations/versions/bc8b7507631f_.py
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/35137d7db7b8_.py
    op.drop_table('services_suv')
    op.drop_table('services_sedan')
========
    op.drop_table('services')
    op.drop_table('vehicle_type')
>>>>>>>> af9ef768e7718c6062d8592fdc2bd9baa6de8554:migrations/versions/bc8b7507631f_.py
    op.drop_table('user')
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
