"""empty message

Revision ID: 35d1d849184e
Revises: c5a69704b89f
Create Date: 2024-05-25 10:23:12.835340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d1d849184e'
down_revision = 'c5a69704b89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
