"""empty message

Revision ID: 3f6bee78f97b
Revises: afe2897c0c60
Create Date: 2024-05-29 17:27:20.622056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6bee78f97b'
down_revision = 'afe2897c0c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_url_media', sa.String(length=1024), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('title_url_media')

    # ### end Alembic commands ###
