"""empty message

Revision ID: 415ad996e62a
Revises: af74b7f776bb
Create Date: 2022-08-24 23:46:34.032588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415ad996e62a'
down_revision = 'af74b7f776bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
