"""empty message

Revision ID: 4275efe9657a
Revises: 763b58f5bf5a
Create Date: 2023-04-19 21:37:53.428756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4275efe9657a'
down_revision = '763b58f5bf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worked_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_workers')
    # ### end Alembic commands ###
