"""empty message

Revision ID: 42ec61210905
Revises: 4570f289f60a
Create Date: 2024-02-27 18:45:20.425849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ec61210905'
down_revision = '4570f289f60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jivamukti_yoga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_of_session', sa.Integer(), nullable=True))
        batch_op.drop_constraint('jivamukti_yoga_type_of_session_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'types_of_session', ['id_type_of_session'], ['id'])
        batch_op.drop_column('type_of_session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jivamukti_yoga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_session', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jivamukti_yoga_type_of_session_fkey', 'types_of_session', ['type_of_session'], ['type'])
        batch_op.drop_column('id_type_of_session')

    # ### end Alembic commands ###
