"""empty message

Revision ID: 454ed134bf80
Revises: c770f547e05b
Create Date: 2023-04-24 09:27:04.127920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454ed134bf80'
down_revision = 'c770f547e05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
