"""empty message

Revision ID: 4570f289f60a
Revises: 8d5f9edac755
Create Date: 2024-02-27 18:43:43.538038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4570f289f60a'
down_revision = '8d5f9edac755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jivamukti_yoga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_session', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('jivamukti_yoga_id_type_of_session_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'types_of_session', ['type_of_session'], ['type'])
        batch_op.drop_column('id_type_of_session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jivamukti_yoga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_of_session', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jivamukti_yoga_id_type_of_session_fkey', 'types_of_session', ['id_type_of_session'], ['id'])
        batch_op.drop_column('type_of_session')

    # ### end Alembic commands ###
