"""empty message

Revision ID: 47d6c8961a5d
Revises: 5ed44cd87d1e
Create Date: 2023-04-22 10:18:04.422700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6c8961a5d'
down_revision = '5ed44cd87d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_workers_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_service', sa.DateTime(), nullable=False),
    sa.Column('end_service', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_workers_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('services_workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('services_workers_workes_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'booking', ['booking_id'], ['id'])
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'])
        batch_op.drop_column('workes_id')

    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('products_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('product_id')

    with op.batch_alter_table('services_workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workes_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('services_workers_workes_id_fkey', 'workers', ['workes_id'], ['id'])
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('booking_id')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('booking')
    # ### end Alembic commands ###
