"""empty message

Revision ID: 4e61517bb1c6
Revises: 85b241beed24
Create Date: 2022-09-06 12:05:29.351447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e61517bb1c6'
down_revision = '85b241beed24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagen', sa.Column('imagen_inmueble_url', sa.String(length=80), nullable=True))
    op.add_column('imagen', sa.Column('imagen_perfil_url', sa.String(length=80), nullable=True))
    op.drop_column('imagen', 'imagen_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagen', sa.Column('imagen_url', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('imagen', 'imagen_perfil_url')
    op.drop_column('imagen', 'imagen_inmueble_url')
    # ### end Alembic commands ###
