"""empty message

Revision ID: 516e5b4554c5
Revises: d628eaf07ed9
Create Date: 2024-08-28 23:17:56.988714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516e5b4554c5'
down_revision = 'd628eaf07ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('calendly_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('calendly_name')

    # ### end Alembic commands ###
