"""empty message

Revision ID: 528b4e32ff84
Revises: 378bbff77115
Create Date: 2022-08-30 08:54:40.913492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528b4e32ff84'
down_revision = '378bbff77115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('received_messages', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'message', ['received_messages'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'received_messages')
    # ### end Alembic commands ###
