"""empty message

Revision ID: 5f6d2e1344d8
Revises: db8bf40c1ec7
Create Date: 2023-07-20 17:52:02.784161

"""
from alembic import op
import sqlalchemy as sa

# 'db8bf40c1ec7'
# revision identifiers, used by Alembic.
revision = '5f6d2e1344d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=250), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_image')
    # ### end Alembic commands ###
