"""empty message

Revision ID: 62953be95e6f
Revises: 2655d9ee9bd4
Create Date: 2024-05-25 20:37:24.624900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62953be95e6f'
down_revision = '2655d9ee9bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_payment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_manager_id_fkey', type_='foreignkey')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_manager_id_fkey', 'manager', ['manager_id'], ['id'])
        batch_op.create_foreign_key('orders_payment_id_fkey', 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###
