"""empty message

Revision ID: 6374e38cc310
Revises: e13e7daacbee
Create Date: 2024-08-09 18:04:13.208407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6374e38cc310'
down_revision = 'e13e7daacbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio_hora', sa.Integer(), nullable=True),
    sa.Column('tecnologias', sa.String(length=200), nullable=True),
    sa.Column('experiencia', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('country')
        batch_op.drop_column('photo')
        batch_op.drop_column('username')
        batch_op.drop_column('name')

    op.drop_table('programador')
    # ### end Alembic commands ###
