"""empty message

Revision ID: 655c55a86431
Revises: 95d0e79d8668
Create Date: 2024-02-13 14:34:43.194245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655c55a86431'
down_revision = '95d0e79d8668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_group', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
