"""empty message

Revision ID: 6626823ec23c
Revises: 19aaa32005c4
Create Date: 2022-05-19 21:29:21.834305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6626823ec23c'
down_revision = '19aaa32005c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.add_column('projects', sa.Column('sale_type', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('bathrooms', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('rooms', sa.Integer(), nullable=False))
    op.drop_column('projects', 'typology')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.add_column('projects', sa.Column('typology', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'rooms')
    op.drop_column('projects', 'bathrooms')
    op.drop_column('projects', 'sale_type')
    op.alter_column('companies', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
