"""empty message

Revision ID: 6681aeef3304
Revises: 5e7b69a3bd1c
Create Date: 2021-03-24 19:06:15.500995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6681aeef3304'
down_revision = '5e7b69a3bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('evaluacion', sa.Integer(), nullable=True))
    op.drop_constraint('comment_id_servicios_prestados_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'id_servicios_prestados')
    op.drop_column('servicios_prestados', 'evaluacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicios_prestados', sa.Column('evaluacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('id_servicios_prestados', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_id_servicios_prestados_fkey', 'comment', 'servicios_prestados', ['id_servicios_prestados'], ['id'])
    op.drop_column('comment', 'evaluacion')
    # ### end Alembic commands ###
