"""empty message

Revision ID: 67eb4edcccf1
Revises: 8e4040b42787
Create Date: 2024-05-29 19:23:27.457768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eb4edcccf1'
down_revision = '8e4040b42787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('video_id',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
