"""empty message

Revision ID: 68578a4e799a
Revises: 1fdfc9d669e2
Create Date: 2024-05-08 11:12:32.090409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68578a4e799a'
down_revision = '1fdfc9d669e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_modelo', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('motor', sa.String(length=50), nullable=False),
    sa.Column('tipo_cambio', sa.String(length=50), nullable=False),
    sa.Column('asientos', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_vehicle_in_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_vehicle_in_rent')
    op.drop_table('favorite_vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
