"""empty message

Revision ID: 69cd44d05f26
Revises: e8e285d7a200
Create Date: 2024-08-07 17:49:33.847644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cd44d05f26'
down_revision = 'e8e285d7a200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])
        batch_op.drop_column('informe_id')

    with op.batch_alter_table('blog_news', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])

    with op.batch_alter_table('blog_recipe', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('blog_news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('baby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('informe_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('report_id')

    # ### end Alembic commands ###
