"""empty message

Revision ID: 6aab4132fe51
Revises: 5a31e9beff57
Create Date: 2022-08-30 03:01:16.116214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aab4132fe51'
down_revision = '5a31e9beff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('encargado', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.drop_table('direccion')
    op.add_column('bebida', sa.Column('nombre', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'bebida', ['nombre'])
    op.add_column('empresa', sa.Column('nombre', sa.String(length=80), nullable=False))
    op.add_column('empresa', sa.Column('telefono', sa.Integer(), nullable=False))
    op.add_column('empresa', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('empresa', sa.Column('direccion', sa.String(length=80), nullable=False))
    op.add_column('empresa', sa.Column('password', sa.String(length=80), nullable=False))
    op.drop_constraint('empresa_nombre_empresa_key', 'empresa', type_='unique')
    op.create_unique_constraint(None, 'empresa', ['direccion'])
    op.create_unique_constraint(None, 'empresa', ['telefono'])
    op.create_unique_constraint(None, 'empresa', ['email'])
    op.create_unique_constraint(None, 'empresa', ['nombre'])
    op.drop_column('empresa', 'nombre_empresa')
    op.add_column('ensalada', sa.Column('nombre', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'ensalada', ['nombre'])
    op.add_column('postre', sa.Column('nombre', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'postre', ['nombre'])
    op.add_column('principal', sa.Column('nombre', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'principal', ['nombre'])
    op.add_column('usuario', sa.Column('nombre', sa.String(length=80), nullable=False))
    op.add_column('usuario', sa.Column('apellido', sa.String(length=80), nullable=False))
    op.add_column('usuario', sa.Column('direccion', sa.String(length=80), nullable=False))
    op.add_column('usuario', sa.Column('casino_id', sa.Integer(), nullable=False))
    op.drop_constraint('usuario_facebook_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_instagram_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_linkedin_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_skype_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_twitter_key', 'usuario', type_='unique')
    op.create_unique_constraint(None, 'usuario', ['direccion'])
    op.drop_constraint('usuario_direccion_id_fkey', 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'casino', ['casino_id'], ['id'])
    op.drop_column('usuario', 'apellido_usuario')
    op.drop_column('usuario', 'twitter')
    op.drop_column('usuario', 'nombre_usuario')
    op.drop_column('usuario', 'skype')
    op.drop_column('usuario', 'administrador')
    op.drop_column('usuario', 'facebook')
    op.drop_column('usuario', 'linkedin')
    op.drop_column('usuario', 'instagram')
    op.drop_column('usuario', 'direccion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('direccion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('instagram', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('linkedin', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('facebook', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('administrador', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('skype', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('nombre_usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('twitter', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('apellido_usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key('usuario_direccion_id_fkey', 'usuario', 'direccion', ['direccion_id'], ['id'])
    op.drop_constraint(None, 'usuario', type_='unique')
    op.create_unique_constraint('usuario_twitter_key', 'usuario', ['twitter'])
    op.create_unique_constraint('usuario_skype_key', 'usuario', ['skype'])
    op.create_unique_constraint('usuario_linkedin_key', 'usuario', ['linkedin'])
    op.create_unique_constraint('usuario_instagram_key', 'usuario', ['instagram'])
    op.create_unique_constraint('usuario_facebook_key', 'usuario', ['facebook'])
    op.drop_column('usuario', 'casino_id')
    op.drop_column('usuario', 'direccion')
    op.drop_column('usuario', 'apellido')
    op.drop_column('usuario', 'nombre')
    op.drop_constraint(None, 'principal', type_='unique')
    op.drop_column('principal', 'nombre')
    op.drop_constraint(None, 'postre', type_='unique')
    op.drop_column('postre', 'nombre')
    op.drop_constraint(None, 'ensalada', type_='unique')
    op.drop_column('ensalada', 'nombre')
    op.add_column('empresa', sa.Column('nombre_empresa', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empresa', type_='unique')
    op.drop_constraint(None, 'empresa', type_='unique')
    op.drop_constraint(None, 'empresa', type_='unique')
    op.drop_constraint(None, 'empresa', type_='unique')
    op.create_unique_constraint('empresa_nombre_empresa_key', 'empresa', ['nombre_empresa'])
    op.drop_column('empresa', 'password')
    op.drop_column('empresa', 'direccion')
    op.drop_column('empresa', 'email')
    op.drop_column('empresa', 'telefono')
    op.drop_column('empresa', 'nombre')
    op.drop_constraint(None, 'bebida', type_='unique')
    op.drop_column('bebida', 'nombre')
    op.create_table('direccion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_calle', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('numero_calle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='direccion_pkey'),
    sa.UniqueConstraint('numero_calle', name='direccion_numero_calle_key')
    )
    op.drop_table('casino')
    # ### end Alembic commands ###
