"""empty message

Revision ID: 6d6bef803a36
Revises: 86c5d6de10bf
Create Date: 2024-04-28 17:59:09.288364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6bef803a36'
down_revision = '86c5d6de10bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_data',
    sa.Column('trainer_data_id', sa.Integer(), nullable=False),
    sa.Column('trainer_name', sa.String(length=50), nullable=False),
    sa.Column('profile_picture', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('trainer_data_id')
    )
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('trainer_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    op.drop_table('trainer_data')
    # ### end Alembic commands ###
