"""empty message

Revision ID: 6ebb67f7e229
Revises: 36dd024d625e
Create Date: 2024-01-09 21:22:23.760214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebb67f7e229'
down_revision = '36dd024d625e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videogame',
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('pegi', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('videogame_id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('admin_nickname', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=250), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('user_name')
        batch_op.drop_column('full_name')

    op.drop_table('admin')
    op.drop_table('videogame')
    # ### end Alembic commands ###
