"""empty message

Revision ID: 6f8da7171354
Revises: 
Create Date: 2022-09-27 22:45:27.226052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8da7171354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casasdecambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrecasa', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.String(length=40), nullable=False),
    sa.Column('moneda', sa.String(length=40), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda'),
    sa.UniqueConstraint('nombrecasa'),
    sa.UniqueConstraint('precio')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('apellido', sa.String(length=40), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('nombrecasa', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nombrecasa'], ['casasdecambio.nombrecasa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrecasa', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.String(length=40), nullable=False),
    sa.Column('moneda', sa.String(length=40), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nombrecasa'], ['casasdecambio.nombrecasa'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasacion')
    op.drop_table('favoritos')
    op.drop_table('user')
    op.drop_table('casasdecambio')
    # ### end Alembic commands ###
