"""empty message

Revision ID: 71434bf37102
Revises: 8f87d2ea294d
Create Date: 2024-09-05 18:56:47.676651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71434bf37102'
down_revision = '8f87d2ea294d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('rating_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('rating_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
