"""empty message

Revision ID: 7321360f04e3
Revises: ee3f7f1c6c4f
Create Date: 2023-08-02 19:00:23.761710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7321360f04e3'
down_revision = 'ee3f7f1c6c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_question', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('secret_answer', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_answer')
        batch_op.drop_column('secret_question')

    # ### end Alembic commands ###
