"""empty message

Revision ID: 73868ee2040b
Revises: 9501e8eb0bf8
Create Date: 2024-05-16 19:01:21.095507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73868ee2040b'
down_revision = '9501e8eb0bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateTime_class', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_class', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('dateTime_class')

    # ### end Alembic commands ###
