"""empty message

Revision ID: 73a28ae87240
Revises: 184c501f4f89
Create Date: 2024-08-26 15:13:06.370804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a28ae87240'
down_revision = '184c501f4f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('calendly_url')

    # ### end Alembic commands ###
