"""empty message

Revision ID: 7625b89edbc0
Revises: 
Create Date: 2024-05-23 19:59:52.040120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7625b89edbc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('marca_modelo', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('motor', sa.String(length=50), nullable=False),
    sa.Column('tipo_cambio', sa.String(length=50), nullable=False),
    sa.Column('asientos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('precio_id_stripe', sa.String(length=50), nullable=False),
    sa.Column('url_img1', sa.String(length=300), nullable=True),
    sa.Column('url_img2', sa.String(length=300), nullable=True),
    sa.Column('url_img3', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_vehicle')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
