"""empty message

Revision ID: 7858e575572a
Revises: 04f1e3627e7e
Create Date: 2024-02-16 23:46:09.131794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7858e575572a'
down_revision = '04f1e3627e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('departments')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('museum_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'museums', ['museum_id'], ['id'])

    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('museum_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'museums', ['museum_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('museum_id')
        batch_op.drop_column('department')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('museum_id')

    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='departments_pkey')
    )
    op.drop_table('museums')
    # ### end Alembic commands ###
