"""empty message

Revision ID: 7929be0d6051
Revises: cc35cc86d2cc
Create Date: 2023-04-25 17:05:09.778625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7929be0d6051'
down_revision = 'cc35cc86d2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.alter_column('pac_num',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('pac')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pac', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('pac_num',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
