"""empty message

Revision ID: 79db6d8211ad
Revises: 
Create Date: 2024-08-09 18:41:52.034641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79db6d8211ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio_hora', sa.Integer(), nullable=True),
    sa.Column('tecnologias', sa.String(length=200), nullable=True),
    sa.Column('experiencia', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('programador')
    # ### end Alembic commands ###
