"""empty message

Revision ID: 7dcc583ea883
Revises: 583701ad5a47
Create Date: 2023-11-30 16:48:31.896094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcc583ea883'
down_revision = '583701ad5a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
