"""empty message

Revision ID: 804e4d97ad69
Revises: ca064de52115
Create Date: 2023-07-11 10:38:14.120189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '804e4d97ad69'
down_revision = 'ca064de52115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('fuel',
               existing_type=postgresql.ENUM('DIESEL', 'GASOLINA', 'HIBRIDO', 'ELECTRICO', name='fuel_type'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('fuel',
               existing_type=postgresql.ENUM('DIESEL', 'GASOLINA', 'HIBRIDO', 'ELECTRICO', name='fuel_type'),
               nullable=True)

    # ### end Alembic commands ###
