"""empty message

Revision ID: 82d31c182180
Revises: c4f64926d95b
Create Date: 2024-08-11 18:44:26.658771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d31c182180'
down_revision = 'c4f64926d95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('precio_hora',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tecnologias',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('experiencia',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('experiencia',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tecnologias',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('precio_hora',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('empleador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
