"""empty message

Revision ID: 84182b993d26
Revises: b944c40e6ea5
Create Date: 2023-07-21 22:55:36.147865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84182b993d26'
down_revision = 'b944c40e6ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint('user_country_key', type_='unique')
        batch_op.drop_constraint('user_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('user_country_key', ['country'])
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
