"""empty message

Revision ID: 847896031fe6
Revises: e4eebde00e23
Create Date: 2022-08-09 00:40:57.688872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847896031fe6'
down_revision = 'e4eebde00e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casino', sa.Column('contraseña_casino', sa.String(length=80), nullable=False))
    op.add_column('casino', sa.Column('mail_casino', sa.String(length=80), nullable=False))
    op.add_column('casino', sa.Column('nombre_casino', sa.String(length=80), nullable=False))
    op.add_column('casino', sa.Column('razon_social', sa.String(length=80), nullable=False))
    op.add_column('casino', sa.Column('rut', sa.Integer(), nullable=False))
    op.add_column('casino', sa.Column('telefono', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'casino', ['razon_social'])
    op.create_unique_constraint(None, 'casino', ['rut'])
    op.create_unique_constraint(None, 'casino', ['telefono'])
    op.create_unique_constraint(None, 'casino', ['mail_casino'])
    op.create_unique_constraint(None, 'casino', ['nombre_casino'])
    op.create_unique_constraint(None, 'casino', ['contraseña_casino'])
    op.drop_constraint('casino_postre_id_fkey', 'casino', type_='foreignkey')
    op.drop_constraint('casino_bebida_id_fkey', 'casino', type_='foreignkey')
    op.drop_constraint('casino_ensalada_id_fkey', 'casino', type_='foreignkey')
    op.drop_constraint('casino_principal_id_fkey', 'casino', type_='foreignkey')
    op.drop_column('casino', 'postre_id')
    op.drop_column('casino', 'principal_id')
    op.drop_column('casino', 'ensalada_id')
    op.drop_column('casino', 'bebida_id')
    op.add_column('colacion', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.drop_constraint('colacion_casino_id_fkey', 'colacion', type_='foreignkey')
    op.create_foreign_key(None, 'colacion', 'menu', ['menu_id'], ['id'])
    op.drop_column('colacion', 'casino_id')
    op.add_column('menu', sa.Column('bebida_id', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('ensalada_id', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('postre_id', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('principal_id', sa.Integer(), nullable=False))
    op.drop_constraint('menu_contraseña_casino_key', 'menu', type_='unique')
    op.drop_constraint('menu_mail_casino_key', 'menu', type_='unique')
    op.drop_constraint('menu_nombre_casino_key', 'menu', type_='unique')
    op.drop_constraint('menu_razon_social_key', 'menu', type_='unique')
    op.drop_constraint('menu_rut_key', 'menu', type_='unique')
    op.drop_constraint('menu_telefono_key', 'menu', type_='unique')
    op.create_foreign_key(None, 'menu', 'ensalada', ['ensalada_id'], ['id'])
    op.create_foreign_key(None, 'menu', 'postre', ['postre_id'], ['id'])
    op.create_foreign_key(None, 'menu', 'principal', ['principal_id'], ['id'])
    op.create_foreign_key(None, 'menu', 'bebida', ['bebida_id'], ['id'])
    op.drop_column('menu', 'mail_casino')
    op.drop_column('menu', 'nombre_casino')
    op.drop_column('menu', 'rut')
    op.drop_column('menu', 'contraseña_casino')
    op.drop_column('menu', 'telefono')
    op.drop_column('menu', 'razon_social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('razon_social', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('telefono', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('contraseña_casino', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('rut', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('nombre_casino', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('mail_casino', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_unique_constraint('menu_telefono_key', 'menu', ['telefono'])
    op.create_unique_constraint('menu_rut_key', 'menu', ['rut'])
    op.create_unique_constraint('menu_razon_social_key', 'menu', ['razon_social'])
    op.create_unique_constraint('menu_nombre_casino_key', 'menu', ['nombre_casino'])
    op.create_unique_constraint('menu_mail_casino_key', 'menu', ['mail_casino'])
    op.create_unique_constraint('menu_contraseña_casino_key', 'menu', ['contraseña_casino'])
    op.drop_column('menu', 'principal_id')
    op.drop_column('menu', 'postre_id')
    op.drop_column('menu', 'ensalada_id')
    op.drop_column('menu', 'bebida_id')
    op.add_column('colacion', sa.Column('casino_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'colacion', type_='foreignkey')
    op.create_foreign_key('colacion_casino_id_fkey', 'colacion', 'casino', ['casino_id'], ['id'])
    op.drop_column('colacion', 'menu_id')
    op.add_column('casino', sa.Column('bebida_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('casino', sa.Column('ensalada_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('casino', sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('casino', sa.Column('postre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('casino_principal_id_fkey', 'casino', 'principal', ['principal_id'], ['id'])
    op.create_foreign_key('casino_ensalada_id_fkey', 'casino', 'ensalada', ['ensalada_id'], ['id'])
    op.create_foreign_key('casino_bebida_id_fkey', 'casino', 'bebida', ['bebida_id'], ['id'])
    op.create_foreign_key('casino_postre_id_fkey', 'casino', 'postre', ['postre_id'], ['id'])
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_constraint(None, 'casino', type_='unique')
    op.drop_column('casino', 'telefono')
    op.drop_column('casino', 'rut')
    op.drop_column('casino', 'razon_social')
    op.drop_column('casino', 'nombre_casino')
    op.drop_column('casino', 'mail_casino')
    op.drop_column('casino', 'contraseña_casino')
    # ### end Alembic commands ###
