"""empty message

Revision ID: 847d0ac96d31
Revises: acf2984b4879
Create Date: 2023-09-12 19:10:25.566402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847d0ac96d31'
down_revision = 'acf2984b4879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
