"""empty message

Revision ID: 871c55207028
Revises: 
Create Date: 2021-03-11 02:36:00.689627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871c55207028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pymes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=10000), nullable=False),
    sa.Column('provincia', sa.String(length=300), nullable=False),
    sa.Column('contacto', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.String(length=1000), nullable=False),
    sa.Column('info_adicional', sa.String(length=10000), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('amenity', sa.String(length=100), nullable=False),
    sa.Column('id_osm', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('respuesta_de_seguridad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mi_pasaporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo_pymes', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mi_pasaporte')
    op.drop_table('user')
    op.drop_table('pymes')
    # ### end Alembic commands ###
