"""empty message

Revision ID: 872673f2afd8
Revises: d217c66a02ff
Create Date: 2024-08-13 18:42:59.684434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872673f2afd8'
down_revision = 'd217c66a02ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bjcp_style',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('IBUs',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('volALC',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('volALC',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('IBUs',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('bjcp_style',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
