"""empty message

Revision ID: 880ab5c6a2f8
Revises: 3d936babb00f
Create Date: 2021-03-24 15:35:10.752620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880ab5c6a2f8'
down_revision = '3d936babb00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_users'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
