"""empty message

Revision ID: 88cd3170c6d5
Revises: 942151debd03
Create Date: 2024-05-05 20:07:49.414345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cd3170c6d5'
down_revision = '942151debd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cash', sa.Boolean(), nullable=False))
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_cash')

    # ### end Alembic commands ###
