"""empty message

Revision ID: 89dc24d25d07
Revises: 7555f74c8d14
Create Date: 2021-04-27 16:28:30.115444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dc24d25d07'
down_revision = '7555f74c8d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermarket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=False),
    sa.Column('information', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.drop_table('advertaisment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertaisment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='advertaisment_pkey')
    )
    op.drop_table('supermarket')
    # ### end Alembic commands ###
