"""empty message

Revision ID: 95815d6a1c32
Revises: 
Create Date: 2021-03-17 18:32:12.458000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95815d6a1c32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pymes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('descripcion', sa.String(length=10485760), nullable=True),
    sa.Column('provincia', sa.String(length=600), nullable=False),
    sa.Column('telefono', sa.String(length=600), nullable=True),
    sa.Column('email', sa.String(length=600), nullable=True),
    sa.Column('horario', sa.String(length=1000), nullable=True),
    sa.Column('imagen', sa.String(length=1000), nullable=False),
    sa.Column('logo', sa.String(length=1000), nullable=True),
    sa.Column('info_adicional', sa.String(length=10485760), nullable=True),
    sa.Column('link_youtube', sa.String(length=1000), nullable=True),
    sa.Column('sitio_web', sa.String(length=1000), nullable=True),
    sa.Column('tipo', sa.String(length=1000), nullable=False),
    sa.Column('categoria', sa.String(length=1000), nullable=False),
    sa.Column('id_osm', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('respuesta_de_seguridad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mi_pasaporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo_pymes', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mi_pasaporte')
    op.drop_table('user')
    op.drop_table('pymes')
    # ### end Alembic commands ###
