"""empty message

Revision ID: 97c1c4cad36a
Revises: 309f1c28a377
Create Date: 2022-06-15 09:50:08.535643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c1c4cad36a'
down_revision = '309f1c28a377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('apellidos', sa.String(length=80), nullable=True),
    sa.Column('razon_social', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('razon_social')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresas')
    # ### end Alembic commands ###
