"""empty message

Revision ID: 98a7929e4507
Revises: d64be378bcc8
Create Date: 2022-06-17 14:18:05.478126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a7929e4507'
down_revision = 'd64be378bcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencers', sa.Column('post4', sa.String(length=120), nullable=True))
    op.add_column('influencers', sa.Column('post5', sa.String(length=120), nullable=True))
    op.add_column('influencers', sa.Column('post6', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencers', 'post6')
    op.drop_column('influencers', 'post5')
    op.drop_column('influencers', 'post4')
    # ### end Alembic commands ###
