"""empty message

Revision ID: 994ef0b42fde
Revises: ed25417d06b9
Create Date: 2021-03-30 00:41:45.360947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994ef0b42fde'
down_revision = 'ed25417d06b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio_registrados', sa.Column('username', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio_registrados', 'username')
    # ### end Alembic commands ###
