"""empty message

Revision ID: 9a18438fddb6
Revises: 7dcc583ea883
Create Date: 2023-11-30 17:22:09.259084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a18438fddb6'
down_revision = '7dcc583ea883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buscador', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
