"""empty message

Revision ID: 9a40c7f8ff7f
Revises: 782b38c227d5
Create Date: 2024-02-25 15:31:53.311288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a40c7f8ff7f'
down_revision = '782b38c227d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_payment_date', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('last_payment_date')

    # ### end Alembic commands ###
