"""empty message

Revision ID: a06ece8d5497
Revises: 6bb7fa41e256
Create Date: 2024-02-27 17:01:09.003562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06ece8d5497'
down_revision = '6bb7fa41e256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ashtanga_yoga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=False),
    sa.Column('asana_focus', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.String(length=120), nullable=False),
    sa.Column('id_type_of_session', sa.Integer(), nullable=True),
    sa.Column('id_instructor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_instructor'], ['instructor.id'], ),
    sa.ForeignKeyConstraint(['id_type_of_session'], ['types_of_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ashtanga_yoga')
    # ### end Alembic commands ###
