"""empty message

Revision ID: a195471db2c4
Revises: ebec6ad61698
Create Date: 2022-08-07 23:04:50.669252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a195471db2c4'
down_revision = 'ebec6ad61698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_casino', sa.String(length=80), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('mail_casino', sa.String(length=80), nullable=False),
    sa.Column('contraseña_casino', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contraseña_casino'),
    sa.UniqueConstraint('mail_casino'),
    sa.UniqueConstraint('nombre_casino'),
    sa.UniqueConstraint('razon_social'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
