"""empty message

Revision ID: ab16a4025eb7
Revises: 50327dae8c7f
Create Date: 2024-05-01 09:54:31.718866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab16a4025eb7'
down_revision = '50327dae8c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historical', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['user_data_id'])
        batch_op.drop_column('historial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historial', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('historical')

    # ### end Alembic commands ###
