"""empty message

Revision ID: af0a7803323b
Revises: 542ae88c9d91
Create Date: 2022-09-25 21:05:26.388538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0a7803323b'
down_revision = '542ae88c9d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contrasena', sa.String(length=80), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'contrasena')
    # ### end Alembic commands ###
