"""empty message

Revision ID: b508cf1180d3
Revises: 713417995dea
Create Date: 2023-06-21 17:13:16.201267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b508cf1180d3'
down_revision = '713417995dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nameandsur', sa.String(length=100), nullable=False))
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_column('nameandsur')

    # ### end Alembic commands ###
