"""empty message

Revision ID: b6fa90fe41fa
Revises: 8f466d081273
Create Date: 2024-05-13 14:38:10.831000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fa90fe41fa'
down_revision = '8f466d081273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_membership_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_membership_history', ['active_membership_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active_membership_id')

    # ### end Alembic commands ###
