"""empty message

Revision ID: bb02f030c265
Revises: c86aae282aaf
Create Date: 2024-08-12 18:14:14.161448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb02f030c265'
down_revision = 'c86aae282aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'empleador', ['empleador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleador_id')

    # ### end Alembic commands ###
