"""empty message

Revision ID: c0dcf96ca9b6
Revises: e06f6bf224ed
Create Date: 2022-06-16 14:37:57.398920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dcf96ca9b6'
down_revision = 'e06f6bf224ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('empresas', 'apellidos',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('empresas', 'bio',
               existing_type=sa.VARCHAR(length=360),
               nullable=False)
    op.alter_column('empresas', 'ciudad',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('empresas', 'nombre',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('empresas', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('empresas', 'razon_social',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('empresas', 'sector',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'apellidos',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'bio',
               existing_type=sa.VARCHAR(length=360),
               nullable=False)
    op.alter_column('influencers', 'categoria',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'ciudad',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'ig_user',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'nombre',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('influencers', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencers', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('influencers', 'nombre',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('influencers', 'ig_user',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('influencers', 'ciudad',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('influencers', 'categoria',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('influencers', 'bio',
               existing_type=sa.VARCHAR(length=360),
               nullable=True)
    op.alter_column('influencers', 'apellidos',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'sector',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'razon_social',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'nombre',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'ciudad',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('empresas', 'bio',
               existing_type=sa.VARCHAR(length=360),
               nullable=True)
    op.alter_column('empresas', 'apellidos',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_table('favoritos')
    # ### end Alembic commands ###
