"""empty message

Revision ID: c2c8a5815b5a
Revises: 4ea263091ed5
Create Date: 2023-05-03 10:26:05.359874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c8a5815b5a'
down_revision = '4ea263091ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('ccaa',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.alter_column('num_ropo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('technician_ccaa_key', type_='unique')
        batch_op.drop_constraint('technician_country_key', type_='unique')
        batch_op.drop_constraint('technician_description_key', type_='unique')
        batch_op.drop_constraint('technician_speciality_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.create_unique_constraint('technician_speciality_key', ['speciality'])
        batch_op.create_unique_constraint('technician_description_key', ['description'])
        batch_op.create_unique_constraint('technician_country_key', ['country'])
        batch_op.create_unique_constraint('technician_ccaa_key', ['ccaa'])
        batch_op.alter_column('num_ropo',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.alter_column('ccaa',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
