"""empty message

Revision ID: c3ae743e9e4c
Revises: 7aab480a20bf
Create Date: 2024-05-15 17:42:14.371886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ae743e9e4c'
down_revision = '7aab480a20bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_membership_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_membership_history', ['active_membership_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active_membership_id')

    # ### end Alembic commands ###
