"""empty message

Revision ID: c408c0143712
Revises: 045ba687af98
Create Date: 2024-02-17 16:08:11.757202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c408c0143712'
down_revision = '045ba687af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_instructor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instructor', ['id_instructor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_instructor')

    # ### end Alembic commands ###
