"""empty message

Revision ID: c52d9d4a0c3c
Revises: d22f3011ab8b
Create Date: 2022-09-04 20:55:21.033774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52d9d4a0c3c'
down_revision = 'd22f3011ab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte__usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.alter_column('semanas', 'lunes',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('semanas', 'martes',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('semanas', 'miercoles',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('semanas', 'jueves',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('semanas', 'viernes',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('semanas', 'viernes',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('semanas', 'jueves',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('semanas', 'miercoles',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('semanas', 'martes',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('semanas', 'lunes',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('reporte__usuario')
    # ### end Alembic commands ###
