"""empty message

Revision ID: cd7211caf692
Revises: 84182b993d26
Create Date: 2023-07-25 20:35:47.079319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7211caf692'
down_revision = '84182b993d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('territory_state', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('territory_state',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('recovery_answer',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('recovery_question',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    op.drop_table('favorites')
    # ### end Alembic commands ###
