"""empty message

Revision ID: cde600977515
Revises: 9534453895a8
Create Date: 2024-05-20 23:29:11.684059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde600977515'
down_revision = '9534453895a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('number_document',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('number_document',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('text_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
