"""empty message

Revision ID: d09af2c9fc00
Revises: bc8b05f6de6a
Create Date: 2024-08-06 18:27:57.841279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09af2c9fc00'
down_revision = 'bc8b05f6de6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_routine_date', schema=None) as batch_op:
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('exercise_day_routine', schema=None) as batch_op:
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('weekly_day_routine', schema=None) as batch_op:
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('weekly_routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('weekly_routine', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_routine', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('weekly_day_routine', schema=None) as batch_op:
        batch_op.alter_column('weekly_routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercise_day_routine', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('day_routine_date', schema=None) as batch_op:
        batch_op.alter_column('day_routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
