"""empty message

Revision ID: d12c88d52b38
Revises: 
Create Date: 2024-05-08 18:43:43.781039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12c88d52b38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trainer_data',
    sa.Column('trainer_data_id', sa.Integer(), nullable=False),
    sa.Column('trainer', sa.Integer(), nullable=True),
    sa.Column('trainer_name', sa.String(length=50), nullable=False),
    sa.Column('profile_picture', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['trainer'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('trainer_data_id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_weight', sa.Integer(), nullable=True),
    sa.Column('user_height', sa.Integer(), nullable=True),
    sa.Column('user_illness', sa.String(length=250), nullable=False),
    sa.Column('user_objetives', sa.String(length=250), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_data.trainer_data_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('exercise_weight', sa.Integer(), nullable=True),
    sa.Column('user_data_id', sa.Integer(), nullable=True),
    sa.Column('trainer_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_data_id'], ['trainer_data.trainer_data_id'], ),
    sa.ForeignKeyConstraint(['user_data_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_name')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_routine', sa.JSON(), nullable=False),
    sa.Column('historical', sa.JSON(), nullable=True),
    sa.Column('user_data_id', sa.Integer(), nullable=False),
    sa.Column('trainer_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_data_id'], ['trainer_data.trainer_data_id'], ),
    sa.ForeignKeyConstraint(['user_data_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_data_id')
    )
    op.create_table('routine_exercise_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_exercise_association')
    op.drop_table('routines')
    op.drop_table('exercise')
    op.drop_table('user_data')
    op.drop_table('trainer_data')
    op.drop_table('user')
    op.drop_table('trainer')
    # ### end Alembic commands ###
