"""empty message

Revision ID: d22f3011ab8b
Revises: df1cc5a1f199
Create Date: 2022-09-04 20:04:35.200021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22f3011ab8b'
down_revision = 'df1cc5a1f199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    op.add_column('semanas', sa.Column('lunes', sa.String(length=80), nullable=False))
    op.add_column('semanas', sa.Column('martes', sa.String(length=80), nullable=False))
    op.add_column('semanas', sa.Column('miercoles', sa.String(length=80), nullable=False))
    op.add_column('semanas', sa.Column('jueves', sa.String(length=80), nullable=False))
    op.add_column('semanas', sa.Column('viernes', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'semanas', ['lunes'])
    op.create_unique_constraint(None, 'semanas', ['martes'])
    op.create_unique_constraint(None, 'semanas', ['miercoles'])
    op.create_unique_constraint(None, 'semanas', ['jueves'])
    op.create_unique_constraint(None, 'semanas', ['viernes'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semanas', type_='unique')
    op.drop_constraint(None, 'semanas', type_='unique')
    op.drop_constraint(None, 'semanas', type_='unique')
    op.drop_constraint(None, 'semanas', type_='unique')
    op.drop_constraint(None, 'semanas', type_='unique')
    op.drop_column('semanas', 'viernes')
    op.drop_column('semanas', 'jueves')
    op.drop_column('semanas', 'miercoles')
    op.drop_column('semanas', 'martes')
    op.drop_column('semanas', 'lunes')
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
