"""empty message

Revision ID: d3346aea46d8
Revises: 
Create Date: 2023-07-14 02:55:18.037496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3346aea46d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(length=450), nullable=True),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('car_name', sa.String(length=50), nullable=True, unique=True),
    sa.ForeignKeyConstraint(['car_name'], ['car.car_name'], ),
    sa.ForeignKeyConstraint(['user_first_name'], ['user.first_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_rating', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['car_name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['first_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('overall_rating')

    op.drop_table('review')
    # ### end Alembic commands ###
