"""empty message

Revision ID: db78379b56fe
Revises: 0bb1477904cb
Create Date: 2023-08-02 20:40:11.192134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db78379b56fe'
down_revision = '0bb1477904cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sizes', ['size_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('size_id')

    # ### end Alembic commands ###
