"""empty message

Revision ID: dcf867106f90
Revises: 8fa2e74d115e
Create Date: 2024-05-21 18:37:18.269080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf867106f90'
down_revision = '8fa2e74d115e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('card_number_last4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cardholder_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_detail', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('product_description')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('cardholder_name')
        batch_op.drop_column('card_type')
        batch_op.drop_column('card_number_last4')
        batch_op.drop_column('description')
        batch_op.drop_column('currency')
        batch_op.drop_column('transaction_reference')
        batch_op.drop_column('confirmation_date')

    # ### end Alembic commands ###
