"""empty message

Revision ID: dd13813352dc
Revises: 50423c65122d
Create Date: 2024-08-26 19:46:17.965850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd13813352dc'
down_revision = '50423c65122d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.alter_column('salario',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.alter_column('salario',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
