"""empty message

Revision ID: dd475daaebbd
Revises: 2763ad07d870
Create Date: 2023-04-05 23:51:57.751969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd475daaebbd'
down_revision = '2763ad07d870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('size34', sa.Integer(), nullable=True),
    sa.Column('size35', sa.Integer(), nullable=True),
    sa.Column('size36', sa.Integer(), nullable=True),
    sa.Column('size37', sa.Integer(), nullable=True),
    sa.Column('size38', sa.Integer(), nullable=True),
    sa.Column('size39', sa.Integer(), nullable=True),
    sa.Column('size40', sa.Integer(), nullable=True),
    sa.Column('size41', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants_transactions')
    # ### end Alembic commands ###
