"""empty message

Revision ID: df1cc5a1f199
Revises: 53f88be71f9f
Create Date: 2022-09-04 19:56:33.239193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1cc5a1f199'
down_revision = '53f88be71f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'dia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
