"""empty message

Revision ID: e5baa635c3ac
Revises: 120ea9887870
Create Date: 2024-08-21 17:05:09.695483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5baa635c3ac'
down_revision = '120ea9887870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.Date(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
