"""empty message

Revision ID: e890e671c6b8
Revises: 
Create Date: 2023-12-15 19:22:36.532649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e890e671c6b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacion',
    sa.Column('idPublicacion', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('comuna', sa.String(length=200), nullable=False),
    sa.Column('rubro', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPublicacion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fecha')
    )
    op.drop_table('user_publicacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_publicacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_publicacion_pkey'),
    sa.UniqueConstraint('fecha', name='user_publicacion_fecha_key')
    )
    op.drop_table('publicacion')
    # ### end Alembic commands ###
