"""empty message

Revision ID: e8ff51b47b05
Revises: 4a66c3e5d66e
Create Date: 2023-12-14 15:47:09.605700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ff51b47b05'
down_revision = '4a66c3e5d66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('patient_first_name_key', type_='unique')
        batch_op.drop_constraint('patient_last_name_key', type_='unique')

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_constraint('specialist_certificate_key', type_='unique')
        batch_op.drop_constraint('specialist_description_key', type_='unique')
        batch_op.drop_constraint('specialist_first_name_key', type_='unique')
        batch_op.drop_constraint('specialist_language_key', type_='unique')
        batch_op.drop_constraint('specialist_last_name_key', type_='unique')
        batch_op.drop_constraint('specialist_picture_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.create_unique_constraint('specialist_picture_key', ['picture'])
        batch_op.create_unique_constraint('specialist_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('specialist_language_key', ['language'])
        batch_op.create_unique_constraint('specialist_first_name_key', ['first_name'])
        batch_op.create_unique_constraint('specialist_description_key', ['description'])
        batch_op.create_unique_constraint('specialist_certificate_key', ['certificate'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_unique_constraint('patient_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('patient_first_name_key', ['first_name'])

    # ### end Alembic commands ###
