"""empty message

Revision ID: ec5387313f9d
Revises: 2eda13b4e123
Create Date: 2024-09-06 00:44:32.313029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5387313f9d'
down_revision = '2eda13b4e123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('rating_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programador', schema=None) as batch_op:
        batch_op.alter_column('rating_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
