"""empty message

Revision ID: f160271dd80f
Revises: 54bc27177e7c
Create Date: 2024-05-25 20:00:31.475940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f160271dd80f'
down_revision = '54bc27177e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trolley', schema=None) as batch_op:
        batch_op.drop_constraint('trolley_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trolley', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('trolley_order_id_fkey', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
