"""empty message

Revision ID: f47bd4c77a6a
Revises: a5c352888806
Create Date: 2024-05-19 18:18:30.938015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47bd4c77a6a'
down_revision = 'a5c352888806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('room_name', sa.String(length=80), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('reviews', sa.String(), nullable=True),
    sa.Column('room_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('xbox', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('psn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('steam', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_play', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nintendo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('epic_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=2042),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=2042),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('admin')
        batch_op.drop_column('gender')
        batch_op.drop_column('bio')
        batch_op.drop_column('epic_id')
        batch_op.drop_column('nintendo')
        batch_op.drop_column('google_play')
        batch_op.drop_column('steam')
        batch_op.drop_column('psn')
        batch_op.drop_column('xbox')
        batch_op.drop_column('languages')
        batch_op.drop_column('timezone')
        batch_op.drop_column('region')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('username')

    op.drop_table('room_participant')
    op.drop_table('room')
    op.drop_table('games')
    # ### end Alembic commands ###
