"""empty message

Revision ID: fabb32a8ea4a
Revises: 69bf538fce99
Create Date: 2023-08-01 22:06:29.007516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabb32a8ea4a'
down_revision = '69bf538fce99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_rating',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='rating_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name='rating_pkey')
    )
    op.drop_table('products_rating')
    # ### end Alembic commands ###
