"""empty message

Revision ID: fd46aef4a380
Revises: dddc3e5c4b03
Create Date: 2023-04-30 13:17:18.812351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd46aef4a380'
down_revision = 'dddc3e5c4b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_constraint('workers_working_schedule_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_unique_constraint('workers_working_schedule_key', ['working_schedule'])

    # ### end Alembic commands ###
