
import click
from api.models import db, User, Sets, Exercise

"""
In this file, you can add as many commands as you want using the @app.cli.command decorator
Flask commands are usefull to run cronjobs or tasks outside of the API but sill in integration 
with youy database, for example: Import the price of bitcoin every night as 12am
"""
def setup_commands(app):
    
    """ 
    This is an example command "insert-test-users" that you can run from the command line
    by typing: $ flask insert-test-users 5
    Note: 5 is the number of users to add
    """
    @app.cli.command("insert-test-users") # name of our command
    @click.argument("count") # argument of out command
    def insert_test_users(count):
        print("Creating test users")
        for x in range(1, int(count) + 1):
            user = User()
            user.email = "test_user" + str(x) + "@test.com"
            user.password = "123456"
            user.is_active = True
            db.session.add(user)
            db.session.commit()
            print("User: ", user.email, " created.")

        print("All test users created")

    @app.cli.command("insert-test-data")
    def insert_test_data():
        try:
            sets = [
                    Sets(sets=4, repetitions=12 ),
                    Sets(sets=4, repetitions=10),
                    Sets(sets=5, repetitions=8),
                    Sets(sets=4, repetitions=15),
                    ]
            db.session.add_all(sets)


            exercises = [
                Exercise(name="Abdominales", description="<ol><li>Acuéstese boca arriba en el suelo con las rodillas dobladas.</li><li>Flexione los hombros hacia la pelvis. Las manos pueden estar detrás o al costado del cuello o cruzadas sobre el pecho.</li><li>Repita.</li></ol>", image="https://wger.de/media/exercise-image/91/Crunches-1.png", category="ABDOMINALES"),
                Exercise(name="Abdominales HD", description="<ol><li>El movimiento crunch es uno de los ejercicios más básicos diseñados para fortalecer los músculos centrales del cuerpo.</li><li>El ejercicio ayuda a fortalecer los músculos centrales, mejorar la postura y aumentar la movilidad y flexibilidad muscular.</li><li>Mejora los músculos del six pack: Cuando se realiza el ejercicio de abdominales, los músculos rectos abdominales y oblicuos se tensan, por lo que se desarrollan los músculos abdominales superiores y los músculos del six pack.</li><li>Aumenta la fuerza de los músculos abdominales: La función principal de los músculos abdominales es estabilizar la sección media. Te apoya mientras levantas objetos pesados, lo que te permite girar y rotar tu cuerpo. Estas son acciones de todo el día que no notas, por lo que es importante que tus músculos abdominales puedan soportar largas horas de trabajo. El ejercicio crunch ayuda a desarrollar esta importante resistencia en los músculos abdominales. La resistencia muscular es la capacidad de estas fibras para resistir la resistencia durante mucho tiempo.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Arremetidas inversas", description="<p>Posición inicial:</p><ol><li>De pie, con los pies separados a la altura de las caderas.</li></ol><p>Pasos:</p><ol><li>Da un paso hacia atrás con una pierna para que pueda doblarse cómodamente hasta un ángulo de 90 grados.</li><li>Doble lentamente ambas rodillas hasta formar un ángulo de 90 grados.</li><li>Vuelva a la posición inicial.</li><li>Repita, alternando las piernas.</li></ol>",  category="PIERNAS"),
                Exercise(name="Asiento en pared", description="<ol><li>Apóyese en la pared, mirando hacia adelante y con los pies plantados firmemente en el suelo, sus hombros deben separarse y estar a 50 centímetros de la pared.</li><li>Deslízate por la pared, manteniendo la espalda presionada a ella, hasta que las piernas estén en ángulo recto. Las rodillas deben estar directamente sobre los tobillos. El dolor en el cuádriceps es normal, deténgase si siente dolor en la rodilla o en la rótula.</li></ol>",  category="PIERNAS"),
                Exercise(name="Barbell Hip Thrust", description="<ol><li>Siéntate en el suelo con un banco detrás de ti.</li><li>Dobla las rodillas para que tus pies estén plantados en el suelo.</li><li>Sujeta una barra que descanse debajo de tus caderas.</li><li>Si tienes una barra acolchada o algo que puedas colocar entre la barra y tu cuerpo, te resultará más cómodo.</li></ol>",  category="PIERNAS"),
                Exercise(name="Biceps con TRX", description="<ol><li>Agarre las asas de las correas TRX.</li><li>Incline el cuerpo hacia atrás, con los brazos y piernas extendidos, cuerpo posicionado en una sola línea.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Biceps concentrado", description="<ol><li>El curl de concentración es un ejercicio clásico para desarrollar los bíceps un brazo a la vez.</li><li>Se puede realizar inclinado o de rodillas, pero se realiza más a menudo sentado en un banco.</li><li>Es excelente para enfatizar el pico del bíceps y, a menudo, se usa para terminar un entrenamiento de bíceps.</li></ol>",  category="BRAZOS"),
                Exercise(name="Bodyweight Squat HD", description="<ol><li>La sentadilla es un tipo de ejercicio de peso corporal.</li><li>Es uno de los ejercicios más populares para la fuerza y el crecimiento muscular.</li><li>La sentadilla es particularmente efectiva para enfocarse en los músculos de la pierna y las caderas.</li><li>Las sentadillas son un ejercicio fácil de hacer para los principiantes.</li><li>Pueden ayudar a fortalecer los músculos de las piernas, tensar los músculos de la cadera y quemar calorías para perder peso.</li><li>Aprieta los glúteos y las piernas durante el ejercicio.</li><li>Las sentadillas son muy efectivas para reafirmar y fortalecer las piernas al actuar sobre los glúteos, los flexores de la cadera, los cuádriceps, los isquiotibiales y los músculos internos del muslo.</li><li>Además, las sentadillas con peso corporal pueden ayudar a dar forma a los glúteos.</li></ol>",  category="CARDIO"),
                Exercise(name="Contragolpe de tríceps con mancuernas", description="<ol><li>Comience con una mancuerna en cada mano y las palmas de las manos hacia el torso.</li><li>Mantenga la espalda recta con una ligera flexión de las rodillas e inclínese hacia adelante por la cintura.</li><li>Tu torso debe estar casi paralelo al piso.</li><li>Asegúrate de mantener la cabeza en alto.</li><li>Tus brazos superiores deben estar cerca de tu torso y paralelos al piso.</li><li>Tus antebrazos deben apuntar hacia el suelo mientras sostienes las pesas.</li><li>Debe haber un ángulo de 90 grados formado entre el antebrazo y la parte superior del brazo.</li><li>Esta es tu posición de inicio.</li><li>Ahora, mientras mantiene la parte superior de sus brazos inmóviles, exhale y use sus tríceps para levantar las pesas hasta que el brazo esté completamente extendido.</li><li>Concéntrese en mover el antebrazo.</li><li>Después de una breve pausa en la contracción superior, inhala y baja lentamente las mancuernas hasta la posición inicial.</li><li>Repita el movimiento la cantidad prescrita de repeticiones.</li><li>Variaciones: este ejercicio también se puede ejecutar con un brazo a la vez, al igual que se realizan las filas de un brazo.</li><li>Además, si le gusta la variedad de un solo brazo, puede usar un mango de polea baja en lugar de una mancuerna para una mejor contracción máxima. En este caso, las palmas deben estar hacia arriba (agarre en supinación) en lugar del torso (agarre neutral).</li></ol>",  category="BRAZOS"),
                Exercise(name="Curl cuadriceps", description="<ol><li>La extensión de piernas es un ejercicio de entrenamiento con pesas de resistencia que se enfoca en el músculo cuádriceps de las piernas.</li><li>El ejercicio se realiza utilizando una máquina llamada Leg Extension Machine.</li><li>Hay varios fabricantes de estas máquinas y cada uno es ligeramente diferente.</li><li>La mayoría de los gimnasios y salas de pesas tendrán la máquina en sus instalaciones.</li><li>La extensión de piernas es un ejercicio aislado dirigido a un grupo muscular específico, los cuádriceps.</li><li>No debe considerarse como un entrenamiento total de piernas, como la sentadilla o el peso muerto.</li><li>El ejercicio consiste en doblar la pierna a la altura de la rodilla y extender las piernas, para luego volver a bajarlas a la posición original.</li></ol>",  category="PIERNAS"),
                Exercise(name="Curl de biceps alterno", description="<ol><li>Posición inicial: Comience de pie con pesas en cada mano, la espalda recta y los pies separados al ancho de las caderas.</li><li>Tus brazos deben estar relajados, apuntando hacia abajo.</li><li>Tus rodillas deben estar ligeramente flexionadas, tus abdominales contraídos y tus hombros hacia abajo.</li><li>Dobla un brazo por el codo, llevando la mancuerna hasta tu hombro.</li><li>La parte superior del brazo debe permanecer inmóvil durante este movimiento.</li><li>Lleva la mancuerna hacia abajo hasta que tu brazo esté en su posición original relajada.</li><li>Repita, cambiando de brazo.</li></ol>",  category="BRAZOS"),
                Exercise(name="Curl de biceps con barra Z", description="<ol><li>Sostenga la barra SZ a la altura de los hombros, la espalda recta, los hombros ligeramente hacia atrás, los brazos estirados.</li><li>Dobla los brazos, elevando el peso, con un movimiento rápido.</li><li>Sin pausa, baja la barra con un movimiento lento y controlado.</li><li>No dejes que tu cuerpo se balancee durante el ejercicio, todo el trabajo lo hacen los bíceps, que son los únicos músculos que deben moverse (presta atención a los codos).</li></ol>",  category="BRAZOS"),
                Exercise(name="Curl de bíceps con mancuerna", description="<ol><li>Sujeta dos pesas, los brazos estirados, las manos a los lados, las palmas hacia dentro.</li><li>Flexiona los brazos y sube el peso con un movimiento rápido.</li><li>Al mismo tiempo, gira los brazos 90 grados al principio del movimiento.</li><li>En el punto más alto, gira un poco las pesas hacia fuera.</li><li>Sin pausa, bájalas lentamente.</li><li>No permitas que tu cuerpo se balancee durante el ejercicio, todo el trabajo lo realizan los bíceps, que son los únicos músculos que deben moverse (presta atención a los codos).</li></ol>", image="https://wger.de/media/exercise-image/81/Biceps-curl-1.png", category="BRAZOS"),
                Exercise(name="Curl de predicador inverso", description="<ol><li>Sentado al revés en un banco de bíceps con un agarre estrecho.</li></ol>",  category="BRAZOS"),
                Exercise(name="Curl femoral", description="<ol><li>El curl de piernas, también conocido como curl de isquiotibiales, es un ejercicio de aislamiento que se enfoca en los músculos isquiotibiales.</li><li>El ejercicio consiste en flexionar la parte inferior de la pierna contra la resistencia hacia las nalgas.</li><li>Otros ejercicios que se pueden utilizar para fortalecer los isquiotibiales son las elevaciones de glúteos y isquiotibiales y el peso muerto.</li></ol>",  category="PIERNAS"),
                Exercise(name="Círculos de brazo", description="<ol><li>Ponte de pie con la espalda recta.</li><li>Lleva los brazos hacia delante, levántalos por encima de la cabeza y luego continúa el movimiento por detrás de la espalda y baja a la posición inicial.</li><li>Sigue haciendo círculos con los brazos como se describe en el paso 2.</li></ol>",  category="BRAZOS"),
                Exercise(name="Dominadas", description="<ol><li>Toma la barra con los brazos a la altura de los hombros y las palmas de las manos hacia el frente.</li><li>Intenta sacar el pecho, apretar el abdomen y tirar con las dorsales para elevarte hacia arriba hasta sobrepasar la barra con la barbilla.</li><li>Intenta mantener el resto del cuerpo completamente estático.</li></ol>",  category="ESPALDA"),
                Exercise(name="Dominadas Supinas", description="<ol><li>Ejercicio en barra de dominadas para fortalecer la musculatura relacionada con el tirón: dorsales.</li><li>En menor medida se trabajan los bíceps.</li></ol>", image="https://wger.de/media/exercise-image/181/Chin-ups-2.png", category="ESPALDA"),
                Exercise(name="Elevaciones de rodillas", description="<ol><li>La elevación de piernas a 90° en la barra es un ejercicio muy intenso en el que intervienen todos los músculos abdominales.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Elevaciones frontales", description="<ol><li>Para ejecutar el ejercicio, el levantador se para con los pies separados al ancho de los hombros y las pesas o los mangos de resistencia se sostienen a los lados con un agarre en pronación (por encima de la cabeza).</li><li>El movimiento consiste en llevar los brazos por delante del cuerpo a la altura de los ojos y con sólo una ligera flexión del codo.</li><li>Esto aísla el músculo deltoides anterior (frente al hombro) y utiliza el deltoides anterior para levantar el peso.</li><li>Al levantar es importante mantener el cuerpo inmóvil para que el deltoides anterior se utilice por completo.</li><li>Si el peso no se puede levantar estando quieto, entonces es demasiado pesado y se necesita un peso menor.</li><li>Es importante mantener una ligera flexión en el codo al levantar, ya que mantener el codo trabado agregará tensión a la articulación del codo y podría causar lesiones.</li><li>También se puede usar un agarre neutral, similar al que se usa en el curl de martillo.</li><li>Con esta variación, el peso se eleva nuevamente al nivel de los ojos, pero en un ángulo de 45 grados desde la parte frontal del cuerpo.</li><li>Esto puede ser beneficioso para las personas con lesiones en el hombro, en particular las relacionadas con el manguito de los rotadores.</li></ol>",  category="HOMBROS"),
                Exercise(name="Elevación de pantorrilla derecha", description="<ol><li>Párese en el suelo o en el borde de un escalón para aumentar el rango de movimiento.</li><li>Levante un pie, colocando la parte superior de su pantorrilla.</li><li>Levante los talones hasta que esté de pie.</li><li>Manténgase en esta posición durante tres segundos, luego baje el pie sin tocar el suelo con el talón.</li></ol>",  category="PANTORRILLAS"),
                Exercise(name="Elevación de pantorrilla izquierda", description="<ol><li>Párese en el suelo o en el borde de un escalón para aumentar el rango de movimiento.</li><li>Levante un pie, colocando la parte superior de su pantorrilla.</li><li>Levante los talones hasta que esté de pie.</li><li>Manténgase en esta posición durante tres segundos, luego baje el pie sin tocar el suelo con el talón.</li></ol>",  category="PANTORRILLAS"),
                Exercise(name="Elevación frontal con cable", description="<ol><li>Colóquese de espaldas a la torre de cable.</li><li>Agarre el cable entre sus piernas con una barra SZ.</li></ol>",  category="HOMBROS"),
                Exercise(name="Elevación tibial anterior", description="<ol><li>Pararse derecho.</li><li>Levantar la punta de los pies, apoyándose sobre el talón.</li></ol>",  category="PANTORRILLAS"),
                Exercise(name="Empuje de tríceps en cable", description="<ol><li>El empuje hacia abajo de la cuerda del cable es un ejercicio popular dirigido a los músculos tríceps.</li><li>Es fácil de aprender y realizar, lo que lo convierte en el favorito de todos, desde principiantes hasta levantadores avanzados.</li><li>Por lo general, se realiza para repeticiones de moderadas a altas, como 8-12 repeticiones o más por serie, como parte de un entrenamiento centrado en la parte superior del cuerpo o en los brazos.</li></ol>",  category="BRAZOS"),
                Exercise(name="Extension de triceps polea", description="<ol><li>Coge el cable, párate con los pies a la altura de los hombros, mantén la espalda recta e inclínate un poco hacia delante.</li><li>Empuja la barra hacia abajo, asegurándote de que los codos no se muevan durante el ejercicio.</li><li>Gira las manos hacia afuera al final y vuelve a la posición inicial sin pausa.</li></ol>",  category="BRAZOS"),
                Exercise(name="Extensión de cuádriceps", description="<ol><li>Es un ejercicio de aislamiento centrado en los cuádriceps, que están formados por cuatro músculos específicos de la parte anterior del muslo: el recto femoral, el vasto lateral, el vasto medio y el vasto intermedio.</li></ol>",  category="PIERNAS"),
                Exercise(name="Extensión de triceps", description="<ol><li>Coloque la barra sobre la cabeza con un agarre en pronación estrecho.</li><li>Baje el antebrazo detrás de la parte superior del brazo con los codos sobre la cabeza.</li><li>Extienda el antebrazo por encima de la cabeza.</li><li>Baja y repite.</li></ol>",  category="BRAZOS"),
                Exercise(name="Face pull", description="<ol><li>Conecte una cuerda a una estación de polea colocada aproximadamente al nivel del pecho.</li><li>Da un paso atrás para que estés soportando el peso con los brazos completamente extendidos y asume una postura escalonada (un pie hacia adelante).</li><li>Doble las rodillas ligeramente para tener una base estable.</li><li>Retraiga las escápulas (apriete el dedo de su compañero con los omóplatos) y tire del centro de la cuerda ligeramente hacia la cara.</li><li>Una buena señal es pensar en separar los extremos de la cuerda, no solo en tirar hacia atrás.</li><li>A medida que se acerca a su cara, gire externamente para que sus nudillos queden mirando hacia el techo.</li><li>Mantenga durante un segundo en la posición superior y baje lentamente.</li></ol>",  category="HOMBROS"),
                Exercise(name="Flexiones a pino", description="<ol><li>Realiza flexiones mientras haces el pino.</li><li>Este ejercicio requiere mucha habilidad y fuerza.</li></ol>",  category="HOMBROS"),
                Exercise(name="Flexiones a rotación", description="<ol><li>Haga una flexión de brazos estándar.</li><li>Gire el cuerpo hacia un lado para que la espalda quede recta, la mano inferior que sostiene el cuerpo esté completamente extendida y sólo las extremidades inferiores toquen el suelo.</li><li>Repita, cambiando de lado en cada repetición.</li></ol>",  category="BRAZOS"),
                Exercise(name="Flexiones de pica", description="<p>Posición de mirada fija:</p><ol><li>Perro mirando hacia abajo: Tu cuerpo debe hacer una forma de V, con la espalda, los brazos y las piernas rectas. Las caderas deben estar en el aire.</li><li>Puedes llegar a esta posición caminando con las manos hacia atrás desde una plancha alta.</li><li>Dobla los codos hacia los lados, manteniendo la espalda y las piernas rectas y acercando la cabeza al suelo.</li><li>Estira los brazos, empujando las caderas hacia atrás y manteniendo la espalda y las piernas rectas.</li><li>Repite la operación.</li></ol>",  category="BRAZOS"),
                Exercise(name="Flexión a pino contra la pared", description="<ol><li>Realiza flexiones a pino contra la pared (pecho cara a la pared).</li><li>Este ejercicio es una progresión de las flexiones a pino.</li><li>Es ideal para ganar fuerza en los deltoides.</li></ol>",  category="HOMBROS"),
                Exercise(name="Fondos", description="<p>Posición inicial:</p><ol><li>Siéntate con los brazos detrás de ti, apoyando la espalda.</li><li>Los dedos deben apuntar hacia adelante.</li><li>Las rodillas deben estar dobladas y los pies juntos.</li></ol><p>Pasos:</p><ol><li>Levanta las caderas del suelo, estirando los brazos.</li><li>Dobla los codos, llevando las caderas hacia abajo.</li><li>Endereza los brazos, volviendo a la posición anterior.</li><li>Repita los pasos 2 y 3.</li></ol><p>Notas:</p><p>La dificultad del ejercicio depende de la altura de las caderas.</p>",  category="BRAZOS"),
                Exercise(name="Fondos en TRX", description="<ol><li>Los fondos se realizan con las manos en cada uno de los agarres de nuestro arnés y despegamos los pies desde el suelo para quedarnos completamente en suspensión.</li><li>Desde ahí, podremos hacer fondos en suspensión exactamente igual que cuando se hacen en anillas o paralelas.</li><li>Uno de los beneficios que tienen los fondos en TRX es que aumentan la inestabilidad y nos hacen realizar un esfuerzo más intenso.</li></ol>",  category="BRAZOS"),
                Exercise(name="Hacer Subir", description="<ol><li>Una flexión de brazos es un ejercicio de calistenia que consiste en levantar y bajar el cuerpo con los brazos.</li><li>Se utilizan comúnmente para desarrollar la fuerza de la parte superior del cuerpo, mejorar la estabilidad central y mejorar la condición física general.</li><li>Las flexiones se pueden realizar prácticamente en cualquier lugar y no requieren equipo especial, lo que las convierte en un ejercicio conveniente para hacer en casa o cuando no tienes acceso a un gimnasio.</li></ol>",  category="PECHO"),
                Exercise(name="Hindu Pushups", description="<ol><li>Ejercicio para fortalecer los hombros y pectorales.</li><li>Su nombre se debe a que se empieza en la postura de Yoga 'Perro boca abajo', pasando a 'Cobra' pero sin apoyar las piernas ni torso en el suelo para finalmente acabar con una flexión normal.</li><li>El ejercicio también se puede realizar hacia atrás (de vuelta a la postura inicial).</li><li>Como variación, tras hacer la flexión, se puede elevar la cadera para volver a la postura del perro boca abajo.</li></ol>",  category="HOMBROS"),
                Exercise(name="Inmersiones De Banco En El Piso HD", description="<ol><li>Los fondos de tríceps en el suelo son un ejercicio compuesto, ya que trabajan varios grupos musculares simultáneamente.</li><li>Aunque este ejercicio de peso corporal se enfoca principalmente en los tríceps, también golpea el pecho y la parte delantera del hombro.</li><li>Los fondos de tríceps en el suelo son uno de los ejercicios más efectivos para aumentar la fuerza de los brazos y también desarrollar músculo magro en la parte superior de los brazos.</li><li>Los fondos de tríceps en el suelo son un ejercicio de cadena cinética cerrada y expresan que haces los movimientos alrededor de un punto fijo. Aumenta la fuerza de compresión en las articulaciones, mejorando así la estabilidad.</li></ol>",  category="BRAZOS"),
                Exercise(name="Jumping Jack HD", description="<ol><li>Los saltos de tijera son un ejercicio pliométrico.</li><li>Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo.</li><li>El salto de tijera se enfoca en el brazo, el hombro, los músculos abdominales, los músculos de la cadera y los flexores de la cadera y también trabaja en los muslos, los tendones de la rodilla y los cuádriceps.</li><li>Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza.</li><li>Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.</li></ol>",  category="CARDIO"),
                Exercise(name="Lagartijas", description="<ol><li>Acuéstese boca abajo.</li><li>Ponga sus manos cerca de sus orejas.</li><li>Usa los brazos para levantar el estómago hasta que los brazos estén rectos, manteniendo la espalda recta.</li><li>Doble los brazos hasta que el pecho casi toque el suelo, asegurándose de que la espalda esté recta.</li><li>Repita desde el paso 3.</li></ol>", image="https://wger.de/media/exercise-image/195/Push-ups-1.png", category="BRAZOS"),
                Exercise(name="Levantamiento de piernas", description="<p>Posición inicial:</p><ol><li>Túmbate de espaldas, con los pies juntos y los brazos a los lados.</li></ol><p>Pasos:</p><ol><li>Dobla las rodillas y luego enderézalas para que apunten hacia arriba.</li><li>Manteniendo las piernas rectas, bájalas juntas sin tocar el suelo. Cuanto más bajes, más intenso será el ejercicio.</li><li>Sube las dos piernas juntas hasta que vuelvan a apuntar hacia arriba.</li><li>Repite desde el paso 2.</li></ol>",  category="PIERNAS"),
                Exercise(name="Media sentadillas derecha", description="<ol><li>Párese con la espalda recta.</li><li>Dé un largo paso adelante con su pierna derecha.</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla izquierda.</li><li>Suba la pelvis.</li><li>Repita desde el paso 3.</li></ol>",  category="PIERNAS"),
                Exercise(name="Media sentadillas izquierda", description="<ol><li>Párese con la espalda recta.</li><li>Dé un largo paso adelante con su pierna izquierda.</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla derecha.</li><li>Suba la pelvis.</li><li>Repita desde el paso 3.</li></ol>",  category="PIERNAS"),
                Exercise(name="Montañeros", description="<p>Posición inicial:</p><ol><li>Comienza en la posición de flexión vertical o plancha alta.</li><li>Las manos deben estar directamente debajo de los hombros.</li><li>Mantenga la cabeza alineada con la espalda, mirando al suelo.</li><li>Los pies deben estar separados a la anchura de las caderas.</li></ol><p>Pasos:</p><ol><li>Mueve una rodilla hacia el centro del cuerpo, hacia los codos, manteniendo la otra pierna extendida.</li><li>Con un movimiento rápido de salto, estira la pierna doblada y tira de la otra rodilla hacia tu cuerpo.</li><li>Sigue repitiendo el paso 2, alternando las piernas.</li></ol><p>Notas:</p><p>Durante todo el ejercicio, la espalda debe permanecer lo más recta posible, evitando una joroba o una espalda flácida.</p>",  category="PECHO"),
                Exercise(name="Oblicuos en TRX", description="<ol><li>Coloque los pies en los estribos y asuma una plancha alta con las manos directamente debajo de los hombros.</li><li>Tire de las rodillas hacia su codo derecho, luego empújelas hacia atrás y al centro.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Patada de rodilla", description="<ol><li>Póngase a cuatro patas.</li><li>Empuje un pie hacia atrás hasta que se extienda completamente, concentrándose en los músculos de los glúteos.</li><li>Quédese un segundo, y luego vuelva a la posición inicial.</li><li>Repita, alternando los pies.</li></ol>",  category="PIERNAS"),
                Exercise(name="Plancha HD", description="<ol><li>Una plancha es un ejercicio isométrico de fuerza central que consiste en mantener una posición similar a una flexión de brazos durante el máximo tiempo posible.</li><li>Se puede incorporar de manera efectiva en regímenes generales de acondicionamiento físico, programas de entrenamiento atlético de alto rendimiento e incluso protocolos de rehabilitación física.</li></ol>",  category="PECHO"),
                Exercise(name="Plancha Lateral HD", description="<ol><li>La plancha lateral es un entrenamiento eficaz para fortalecer el tronco.</li><li>Puede ayudarlo a fortalecer y desarrollar los músculos de la parte superior e inferior del cuerpo.</li><li>Al ser un movimiento multifuncional, este ejercicio se enfoca no solo en los músculos abdominales, sino también en la columna vertebral y los glúteos.</li><li>La plancha fortalece y tensa todo el cuerpo, mejora la postura y el equilibrio, reduce la grasa corporal y puede ayudar a acelerar el metabolismo.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Plancha a una mano alterna", description="<ol><li>En la posición de plancha correcta, coloque los pies a una distancia ligeramente superior a la anchura de los hombros.</li><li>Levante y toque alternativamente el hombro opuesto con una mano.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Plancha de antebrazo", description="<p>Posición de salida:</p><ol><li>Empiece a cuatro patas.</li><li>Los brazos deben estar doblados en ángulo recto, con los hombros justo sobre los codos.</li><li>La espalda debe estar recta, todo el cuerpo en línea recta.</li></ol><p>Pasos:</p><ol><li>Mantenga esta posición.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Plancha de lado derecho", description="<ol><li>Acuéstese sobre su lado derecho, con el codo en ángulo recto y el brazo hacia afuera.</li><li>Levante la pelvis del suelo levantando el hombro hacia arriba, manteniendo el antebrazo en el suelo; la cabeza, la pelvis y los pies deben estar en línea recta.</li><li>Mantenga esta posición.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Plancha de lado izquierdo", description="<ol><li>Acuéstese sobre su lado izquierdo, con el codo en ángulo recto y el brazo hacia afuera.</li><li>Levante la pelvis del suelo levantando el hombro hacia arriba, manteniendo el antebrazo en el suelo; la cabeza, la pelvis y los pies deben estar en línea recta.</li><li>Mantenga esta posición.</li></ol>",  category="ABDOMINALES"),
                Exercise(name="Polichilenas", description="<ol><li>Párese con los pies juntos y los brazos a los lados.</li><li>Salte a una posición con las piernas abiertas y las manos tocándose por encima de la cabeza.</li><li>Repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Prensa de piernas", description="<ol><li>La prensa de piernas es un ejercicio de entrenamiento con pesas en el que el individuo empuja un peso o una resistencia con las piernas.</li></ol>",  category="PIERNAS"),
                Exercise(name="Prensa de piernas cerrada", description="<ol><li>El ejercicio es muy similar a la prensa de pierna ancha:</li><li>Siéntese en la máquina y coloque los pies en la plataforma tan separados que podría poner otro pie entre ellos. Los pies son paralelos y apuntan hacia arriba.</li><li>Baje tanto el peso, que las rodillas formen un ángulo recto. Vuelva a empujar inmediatamente la plataforma hacia arriba, sin ninguna pausa.</li><li>Cuando esté en la posición más baja, las rodillas apuntan un poco hacia afuera y el movimiento debe ser siempre fluido.</li></ol>",  category="PIERNAS"),
                Exercise(name="Press Banca Sentado", description="<ol><li>Ponga la máquina de press de pecho para que al sentarse los agarres estén alineados con la parte inferior del pecho.</li><li>Asegúrese de que está sentado con la espalda bien pegada al asiento.</li><li>Agarre una manija con cada mano, saque el pecho hacia afuera, mantenga la cabeza contra el reposacabezas.</li><li>Respire profundamente y empuje lentamente las manijas hacia adelante hasta que sus brazos estén casi completamente extendidos.</li><li>Haga una pausa justo antes del bloqueo, y luego regrese lentamente las manijas a la posición inicial.</li><li>Haga una pausa justo antes de que las manijas se detengan completamente y realice otra repetición.</li></ol>",  category="PECHO"),
                Exercise(name="Press de banca inclinado", description="<ol><li>Realice el press de banca inclinado con una barra fija.</li></ol>",  category="PECHO"),
                Exercise(name="Press de piernas abierto", description="<ol><li>Siéntese en la máquina y coloque los pies en la plataforma, un poco más anchos que los hombros. Los pies están girados hacia afuera unos pocos grados.</li><li>Baje tanto el peso, que las rodillas formen un ángulo recto. Vuelva a empujar inmediatamente la plataforma hacia arriba, sin ninguna pausa.</li><li>Cuando esté en la posición más baja, las rodillas apuntan un poco hacia afuera y el movimiento debe ser siempre fluido.</li></ol>",  category="PIERNAS"),
                Exercise(name="Press de tríceps sentado", description="<ol><li>Siéntese boca arriba (mejor con respaldo).</li><li>Tome una mancuerna firmemente con ambas manos y sosténgala con los brazos extendidos sobre su cabeza.</li><li>Con las palmas de las manos hacia arriba y sosteniendo el peso de la mancuerna, baje lentamente el peso detrás de la cabeza.</li></ol>",  category="BRAZOS"),
                Exercise(name="Press militar", description="<ol><li>En una barra SZ, tome sus manos en el exterior de cada curva y párese con los brazos rectos hacia abajo, con las palmas hacia las piernas.</li><li>Tire de la barra (doblando los brazos por el codo) hacia el pecho y empuje la barra por encima de la cabeza (los brazos lo más rectos posible).</li><li>Regrese la barra a su pecho dejando caer los brazos a la altura de los codos.</li><li>Regrese la barra a su posición original (párese con los brazos hacia abajo, las palmas hacia las piernas).</li></ol>",  category="HOMBROS"),
                Exercise(name="Remo con mancuernas", description="<ol><li>Con las mancuernas en la mano, flexiona la cadera hasta que las manos cuelguen justo por debajo de las rodillas (similar a la posición inicial de pierna recta).</li><li>Mantenga constante el ángulo de la parte superior del cuerpo mientras contrae los músculos dorsales para llevar los codos hacia atrás, pellizcando los omóplatos en la parte superior.</li><li>Intenta no levantarte en cada repetición, comprueba que las manos quedan por debajo de las rodillas en cada repetición.</li></ol>",  category="ESPALDA"),
                Exercise(name="Remo con polea", description="<ol><li>Siéntate y apoya los pies en los puntos de apoyo.</li><li>Agarra la barra con un agarre amplio.</li><li>Tira de la pesa con un movimiento rápido hacia el ombligo, no hacia arriba.</li><li>Durante el movimiento, mantén los brazos y los codos pegados al cuerpo.</li><li>Junta los hombros.</li><li>Deja que el peso baje lentamente hasta que tus brazos estén completamente estirados.</li></ol>",  category="ESPALDA"),
                Exercise(name="Rodillas elevadas", description="<ol><li>Trote en el lugar, levantando las rodillas tan alto como pueda.</li><li>Cambie de pierna a un ritmo rápido.</li></ol>",  category="CARDIO"),
                Exercise(name="Saltar la cuerda: saltos básicos", description="<p>Este ejercicio requiere una cuerda para saltar. Asegúrate de que la longitud de la cuerda se ajusta a tu altura. Una forma de comprobarlo es agarrar las dos asas con una mano y situarse en el centro de la cuerda colgando del suelo con un pie. Si la cuerda (excluyendo las asas) te llega justo por debajo del pecho, su longitud es la adecuada. Una cuerda más corta sería peligrosa, ya que podrías golpearte, y una cuerda más larga sería una mala forma.</p><ol><li>Pon los pies juntos, dobla un poco las rodillas, mantén la cabeza y el cuerpo rectos, mantén los codos dentro, abre los brazos.</li><li>Gira sólo las muñecas con la fuerza suficiente para hacer girar la cuerda.</li><li>Salta lo suficiente para pasar la cuerda por debajo de tus pies.</li><li>Repite desde el paso 2.</li></ol>",  category="CARDIO"),
                Exercise(name="Salto de Tijera HD", description="<ol><li>Los saltos de tijera son un ejercicio pliométrico. Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo.</li><li>El salto de tijera se enfoca en el brazo, el hombro, los músculos abdominales, los músculos de la cadera y los flexores de la cadera y también trabaja en los muslos, los tendones de la rodilla y los cuádriceps.</li><li>Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza.</li><li>Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.</li></ol>",  category="CARDIO"),
                Exercise(name="Saltos Altos De Rodilla HD", description="<ol><li>Puedes utilizar este ejercicio tanto como calentamiento dinámico antes de entrenar como añadirlo a tu rutina de entrenamiento cardiovascular para quemar grasa.</li><li>Los saltos altos de rodilla son un ejercicio pliométrico. Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo.</li><li>Los saltos altos de rodilla se dirigen a los oblicuos, los músculos de las piernas, los músculos de la cadera y los flexores de la cadera y también trabajan en los muslos, los tendones de la rodilla, los cuádriceps y los hombros.</li><li>Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza. Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.</li></ol>",  category="CARDIO"),
                Exercise(name="Sentadilla HD", description="<ol><li>La sentadilla es un tipo de ejercicio de peso corporal. Es uno de los ejercicios más populares para la fuerza y el crecimiento muscular.</li><li>La sentadilla es particularmente efectiva para enfocarse en los músculos de la pierna y las caderas.</li><li>Las sentadillas son un ejercicio fácil de hacer para los principiantes.</li><li>Pueden ayudar a fortalecer los músculos de las piernas, tensar los músculos de la cadera y quemar calorías para perder peso.</li><li>Aprieta los glúteos y las piernas. Las sentadillas son muy efectivas para reafirmar y fortalecer las piernas al actuar sobre los glúteos, los flexores de la cadera, los cuádriceps, los isquiotibiales y los músculos internos del muslo.</li><li>Además, las sentadillas con peso corporal pueden ayudar a dar forma a los glúteos.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadilla búlgara derecha", description="<ol><li>Póngase de pie delante de una silla y dé un largo paso. Ponga la parte superior de su pie derecho en la silla.</li><li>Doble la rodilla delantera, balanceando los brazos hasta que la rodilla trasera casi toque el suelo.</li><li>Empuje hacia atrás a la posición inicial y repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadilla búlgara izquierda", description="<ol><li>Póngase de pie delante de una silla y dé un largo paso. Ponga la parte superior de su pie izquierdo en la silla.</li><li>Doble la rodilla delantera, balanceando los brazos hasta que la rodilla trasera casi toque el suelo.</li><li>Empuje hacia atrás a la posición inicial y repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadilla de lado derecho", description="<ol><li>Póngase de pie y dé un amplio paso lateral hacia la derecha, un poco más grande que el ancho de los hombros.</li><li>Doble la rodilla derecha hasta que su muslo esté paralelo al suelo. La rodilla doblada debe estar en línea con el pie.</li><li>Vuelva a la posición inicial y repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadilla de lado izquierdo", description="<ol><li>Póngase de pie y dé un amplio paso lateral hacia la izquierda, un poco más grande que el ancho de los hombros.</li><li>Doble la rodilla izquierda hasta que su muslo esté paralelo al suelo. La rodilla doblada debe estar en línea con el pie.</li><li>Vuelva a la posición inicial y repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadillas", description="<ol><li>Levántese con los pies separados al ancho de los hombros.</li><li>Mueva las caderas hacia atrás y doble las rodillas y caderas para bajar el torso.</li><li>Repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadillas en pistol derecha", description="<ol><li>Párese en una pierna, con la otra pierna estirada y ligeramente hacia adelante.</li><li>Doble la rodilla lentamente, bajando en sentadilla y manteniendo la espalda y la otra pierna estirada.</li><li>Levántese lentamente de la sentadilla, enderezando la rodilla doblada y manteniendo la otra pierna recta.</li><li>Repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Sentadillas en pistol izquierda", description="<ol><li>Párese en una pierna, con la otra pierna estirada y ligeramente hacia adelante.</li><li>Doble la rodilla lentamente, bajando en sentadilla y manteniendo la espalda y la otra pierna estirada.</li><li>Levántese lentamente de la sentadilla, enderezando la rodilla doblada y manteniendo la otra pierna recta.</li><li>Repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="Squat con barra", description="<ol><li>Controla la bajada, baja en 2 segundos y sube lo más explosivo que puedas.</li><li>Es muy importante que hagas movilidad de cadera antes de empezar a entrenar, para mejorar la profundidad.</li><li>Olvídate del peso, baja todo lo que puedas, sin levantar los talones del suelo y sube hacia arriba.</li><li>Una buena técnica va a generarte más hipertrofia que mucho peso sin un ROM correcto.</li></ol>",  category="PIERNAS"),
                Exercise(name="Subida a peldaño", description="<ol><li>Párese frente a una silla.</li><li>Súbase a la silla.</li><li>Bájese de la silla.</li><li>Repita.</li></ol>",  category="PIERNAS"),
                Exercise(name="TRX - curl de bíceps a un brazo", description="<ol><li>Coloque las cintas cruzadas para dejar toda la fuerza en una sola cuerda y que sea más seguro el ejercicio.</li><li>Colóquese inclinado lateralmente, con el brazo que va a trabajar agarrando la cinta del TRX y el otro brazo relajado.</li><li>El cuerpo debe permanecer recto, mirando al frente, y cuanto más se incline, mayor será la resistencia.</li><li>Ambas piernas estarán juntas mientras el brazo estirado se dobla por el codo, activando el bíceps.</li></ol>",  category="BRAZOS"),
                Exercise(name="TRX- biceps gorila", description="<ol><li>Colóquese de frente a las cintas del TRX y agárrelas con los puños de las manos enfrentados y al frente, con los brazos estirados a la altura de los hombros.</li><li>El cuerpo debe estar recto hacia atrás, y mediante la activación de los bíceps, eleve el cuerpo hacia las cintas del TRX.</li><li>Mantenga el cuerpo recto y los pies apoyados en el suelo.</li><li>Coloque los brazos abiertos hacia los lados, a la altura del pecho, y haga una contracción hacia el pecho doblando los codos para atraer el cuerpo hacia las cintas.</li></ol>",  category="BRAZOS"),
                Exercise(name="Tirar de cables sentados", description="<ol><li>Siéntese e inclínese hacia adelante.</li><li>Mantenga los codos pegados al cuerpo en el lado negativo del movimiento.</li></ol>",  category="ESPALDA"),
                Exercise(name="Zancadas con peso", description="<ol><li>Párese con la espalda recta.</li><li>Dé un gran paso adelante con su pierna izquierda.</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla derecha.</li><li>Vuelva a subir la pelvis.</li><li>Vuelva a la posición con el pie hacia atrás.</li><li>Repita, cambiando de pierna cada vez.</li></ol>",  category="PIERNAS"),
                Exercise(name="extensiones de triceps con trx", description="<ol><li>Suspenda su TRX a la altura de la rodilla. Agarre las asas con un agarre prono y coloque sus piernas juntas detrás de usted.</li><li>Su posición debe ser similar a una posición de push up, con el cuerpo en línea recta y los brazos extendidos.</li><li>Contraiga el suelo pélvico y el core mientras mantiene el cuerpo recto. Mueva las manos para colocarlas juntas, con las cuerdas del TRX justo por encima de su cabeza.</li><li>Comience a bajar doblando los codos hasta que las manos toquen la frente.</li><li>No separe los codos entre sí y asegúrese de que solo se mueven los codos durante el ejercicio.</li><li>Empuje su torso hacia la posición inicial apretando el resto del cuerpo mientras exhala.</li></ol>",  category="BRAZOS"),
                Exercise(name="flexiones en TRX", description="<ol><li>Las flexiones de brazos en TRX añaden un componente de inestabilidad que hará que tus hombros y pectorales trabajen de manera diferente.</li><li>Puedes hacer que el ejercicio sea más o menos intenso colocando tu cuerpo más paralelo o menos al suelo.</li><li>Evita que tus brazos rocen con las cuerdas para prevenir rozaduras y moratones después del entrenamiento.</li></ol>",  category="CARDIO"),
            ]
            db.session.add_all(exercises)

            db.session.commit()
            print(f"DB poblada con exito")
        except Exception as e:
            print(f"Error al poblar la DB: {e}")