
import click
from api.models import db, User, Sets, Exercise

"""
In this file, you can add as many commands as you want using the @app.cli.command decorator
Flask commands are usefull to run cronjobs or tasks outside of the API but sill in integration 
with youy database, for example: Import the price of bitcoin every night as 12am
"""
def setup_commands(app):
    
    """ 
    This is an example command "insert-test-users" that you can run from the command line
    by typing: $ flask insert-test-users 5
    Note: 5 is the number of users to add
    """
    @app.cli.command("insert-test-users") # name of our command
    @click.argument("count") # argument of out command
    def insert_test_users(count):
        print("Creating test users")
        for x in range(1, int(count) + 1):
            user = User()
            user.email = "test_user" + str(x) + "@test.com"
            user.password = "123456"
            user.is_active = True
            db.session.add(user)
            db.session.commit()
            print("User: ", user.email, " created.")

        print("All test users created")

    @app.cli.command("insert-test-data")
    def insert_test_data():
        try:
            all_sets = Sets.query.first()
            all_exercises = Exercise.query.first()

            if not all_sets and not all_exercises:

                sets = [
                        Sets(sets=4, repetitions=10),
                        Sets(sets=4, repetitions=12 ),
                        Sets(sets=4, repetitions=15),
                        Sets(sets=5, repetitions=8),
                        Sets(sets=5, repetitions=10),
                        ]
                db.session.add_all(sets)


                exercises = [
                    Exercise(name="Abdominales", description="Siéntese en una colchoneta, sus pantorrillas descansan en un banco, las rodillas forman un ángulo recto. Mantenga sus manos detrás de su cuello. Sube ahora con un movimiento de balanceo de tu espalda, debes sentir cómo las vértebras individuales pierden contacto con la colchoneta. En el punto más alto, contrae los abdominales tanto como puedas y mantenlos allí durante 2 segundos. Baja ahora, desenrollando tu espalda.", image="https://wger.de/media/exercise-images/591/aca68eb7-b924-4ff1-a76b-7e075c73ec0c.png", category="ABDOMINALES"),
                    Exercise(name="Abdominales HD", description="El movimiento crunch es uno de los ejercicios más básicos diseñados para fortalecer los músculos centrales del cuerpo. El ejercicio ayuda a fortalecer los músculos centrales, mejorar la postura y aumentar la movilidad y flexibilidad muscular. Mejora los músculos del six pack: Cuando se realiza el ejercicio de abdominales, los músculos rectos abdominales y oblicuos se tensan, por lo que se desarrollan los músculos abdominales superiores y los músculos del six pack. Aumenta la fuerza de los músculos abdominales: La función principal de los músculos abdominales es estabilizar la sección media. Te apoya mientras levantas objetos pesados, lo que te permite girar y rotar tu cuerpo. Estas son acciones de todo el día que no notas, por lo que es importante que tus músculos abdominales puedan soportar largas horas de trabajo. El ejercicio crunch ayuda a desarrollar esta importante resistencia en los músculos abdominales. La resistencia muscular es la capacidad de estas fibras para resistir la resistencia durante mucho tiempo.", image="https://wger.de/media/exercise-images/1319/896fe849-f0cc-4955-8bc4-032daebd123f.gif", category="ABDOMINALES"),
                    Exercise(name="Arremetidas inversas", description="<p>Posición inicial:</p><p>De pie, con los pies separados a la altura de las caderas.</p><p>Pasos:</p><ol><li>Da un paso hacia atrás con una pierna para que pueda doblarse cómodamente hasta un ángulo de 90 grados.</li><li>Doble lentamente ambas rodillas hasta formar un ángulo de 90 grados.</li><li>Vuelva a la posición inicial.</li><li>Repita, alternando las piernas.</li></ol>", image="https://wger.de/media/exercise-images/999/d0931eb3-8db0-4049-bb08-aa4036072056.jfif", category="PIERNAS"),
                    Exercise(name="Asiento en pared", description="<ol><li>Apóyese en la pared, mirando hacia adelante y con los pies plantados firmemente en el suelo, sus hombros deben separarse y estar a 50 centímetros de la pared</li><li>Deslízate por la pared, manteniendo la espalda presionada a ella, hasta que las piernas estén en ángulo recto. Las rodillas deben estar directamente sobre los tobillosEl dolor en el cuádriceps es normal, deténgase si siente dolor en la rodilla o en la rótula</li></ol>",   category="PIERNAS"),
                    Exercise(name="Barbell Hip Thrust", description="Siéntate en el suelo con un banco detrás de ti, dobla las rodillas para que tus pies estén plantados en el suelo y sujeta una barra que descanse debajo de tus caderas. Si tienes una barra acolchada o algo que puedas colocar entre la barra y tu cuerpo, te resultará más cómodo.", image="https://wger.de/media/exercise-images/294/2ea6fd82-46f7-4f9a-97e5-b704e6efc469.gif", category="PIERNAS"),
                    Exercise(name="Biceps con TRX", description="músculos implicados: bíceps Agarre las asas de las correas TRX, incline el cuerpo hacia atrás, brazos y piernas extendidos, cuerpo posicionado en una sola línea. (no es de abdominales, es de brazos)", image="https://wger.de/media/exercise-images/958/947ac249-475d-44ed-bed3-8dc433374f59.png", category="ABDOMINALES"),
                    Exercise(name="Biceps concentrado", description="El curl de concentración es un ejercicio clásico para desarrollar los bíceps un brazo a la vez. Se puede realizar inclinado o de rodillas, pero se realiza más a menudo sentado en un banco. Es excelente para enfatizar el pico del bíceps y, a menudo, se usa para terminar un entrenamiento de bíceps.", image="https://wger.de/media/exercise-images/1109/00b0a0bf-c14a-4f13-bb14-62c09030a1aa.png", category="BRAZOS"),
                    Exercise(name="Bodyweight Squat HD", description="La sentadilla es un tipo de ejercicio de peso corporal. Es uno de los ejercicios más populares para la fuerza y el crecimiento muscular. La sentadilla es particularmente efectiva para enfocarse en los músculos de la pierna y las caderas. Las sentadillas son un ejercicio fácil de hacer para los principiantes. Puede ayudar a fortalecer los músculos de las piernas, tensar los músculos de la cadera y quemar calorías para perder peso. Aprieta los glúteos y las piernas. Las sentadillas son muy efectivas para reafirmar y fortalecer las piernas al actuar sobre los glúteos, los flexores de la cadera, los cuádriceps, los isquiotibiales y los músculos internos del muslo. Además, las sentadillas con peso corporal pueden ayudar a dar forma a los glúteos.",   category="CARDIO"),
                    Exercise(name="Contragolpe de tríceps con mancuernas", description="Comience con una mancuerna en cada mano y las palmas de las manos hacia el torso. Mantenga la espalda recta con una ligera flexión de las rodillas e inclínese hacia adelante por la cintura. Tu torso debe estar casi paralelo al piso. Asegúrate de mantener la cabeza en alto. Tus brazos superiores deben estar cerca de tu torso y paralelos al piso. Tus antebrazos deben apuntar hacia el suelo mientras sostienes las pesas. Debe haber un ángulo de 90 grados formado entre el antebrazo y la parte superior del brazo. Esta es tu posición de inicio. Ahora, mientras mantiene la parte superior de sus brazos inmóviles, exhale y use sus tríceps para levantar las pesas hasta que el brazo esté completamente extendido. Concéntrese en mover el antebrazo. Después de una breve pausa en la contracción superior, inhala y baja lentamente las mancuernas hasta la posición inicial. Repita el movimiento la cantidad prescrita de repeticiones. Variaciones: este ejercicio también se puede ejecutar con un brazo a la vez, al igual que se realizan las filas de un brazo. Además, si le gusta la variedad de un solo brazo, puede usar un mango de polea baja en lugar de una mancuerna para una mejor contracción máxima. En este caso, las palmas deben estar hacia arriba (agarre en supinación) en lugar del torso (agarre neutral).", image="https://wger.de/media/exercise-images/655/2b54e1a6-f656-4b0a-9272-1d089fe7d4d3.png", category="BRAZOS"),
                    Exercise(name="Curl cuadriceps", description="La extensión de piernas es un ejercicio de entrenamiento con pesas de resistencia que se enfoca en el músculo cuádriceps de las piernas. El ejercicio se realiza utilizando una máquina llamada Leg Extension Machine. Hay varios fabricantes de estas máquinas y cada uno es ligeramente diferente. La mayoría de los gimnasios y salas de pesas tendrán la máquina en sus instalaciones. La extensión de piernas es un ejercicio aislado dirigido a un grupo muscular específico, los cuádriceps. No debe considerarse como un entrenamiento total de piernas, como la sentadilla o el peso muerto. El ejercicio consiste en doblar la pierna a la altura de la rodilla y extender las piernas, para luego volver a bajarlas a la posición original.", image="https://wger.de/media/exercise-images/369/78c915d1-e46d-4d30-8124-65d68664c3ef.png", category="PIERNAS"),
                    Exercise(name="Curl de biceps alterno", description="Posición inicial: Comience de pie con pesas en cada mano, la espalda recta y los pies separados al ancho de las caderas. Tus brazos deben estar relajados, apuntando hacia abajo. Tus rodillas deben estar ligeramente flexionadas, tus abdominales contraídos y tus hombros hacia abajo.&nbsp;Pasos:&nbsp; 1. Dobla un brazo por el codo, llevando la mancuerna hasta tu hombro. La parte superior del brazo debe permanecer inmóvil durante este movimiento. 2. Lleva la mancuerna hacia abajo hasta que tu brazo esté en su posición original relajada.&nbsp; 3. Repita, cambiando de brazo.", image="https://wger.de/media/exercise-images/1012/8270fdb8-28f1-4eff-b410-af8642085b3f.png", category="BRAZOS"),
                    Exercise(name="Curl de biceps con barra Z", description="Sostenga la barra SZ a la altura de los hombros, la espalda recta, los hombros ligeramente hacia atrás, los brazos estirados. Dobla los brazos, elevando el peso, con un movimiento rápido. Sin pausa, baja la barra con un movimiento lento y controlado. No dejes que tu cuerpo se balancee durante el ejercicio, todo el trabajo lo hacen los bíceps, que son los únicos músculos que deben moverse (presta atención a los codos).", image="https://wger.de/media/exercise-images/94/6dee2f60-aea2-4f2d-9bf6-aef50c4f9483.png", category="BRAZOS"),
                    Exercise(name="Curl de bíceps con mancuerna", description="Sujeta dos pesas, los brazos estirados, las manos a los lados, las palmas hacia dentro. Flexiona los brazos y sube el peso con un movimiento rápido. Al mismo tiempo, gira los brazos 90 grados al principio del movimiento. En el punto más alto, gira un poco las pesas hacia fuera. Sin pausa, bájalas lentamente.No permitas que tu cuerpo se balancee durante el ejercicio, todo el trabajo lo realizan los bíceps, que son los únicos músculos que deben moverse (presta atención a los codos).", image="https://wger.de/media/exercise-images/81/Biceps-curl-1.png", category="BRAZOS"),
                    Exercise(name="Curl de predicador inverso", description="Sentado al revés en un banco de bíceps con un agarre estrecho",   category="BRAZOS"),
                    Exercise(name="Curl femoral", description="El curl de piernas, también conocido como curl de isquiotibiales, es un ejercicio de aislamiento que se enfoca en los músculos isquiotibiales. El ejercicio consiste en flexionar la parte inferior de la pierna contra la resistencia hacia las nalgas. Otros ejercicios que se pueden utilizar para fortalecer los isquiotibiales son las elevaciones de glúteos y isquiotibiales y el peso muerto.", image="https://wger.de/media/exercise-images/364/b318dde9-f5f2-489f-940a-cd864affb9e3.png", category="PIERNAS"),
                    Exercise(name="Círculos de brazo", description="<ol><li>Ponte de pie con la espalda recta.</li><li>Lleva los brazos hacia delante, levántalos por encima de la cabeza y luego continúa el movimiento por detrás de la espalda y baja a la posición inicial.</li><li>Siga haciendo círculos con los brazos como se describe en el paso 2.</li></ol>",   category="BRAZOS"),
                    Exercise(name="Dominadas", description="Toma la barra con los brazos a la altura de los hombros y las palmas de las manos hacia el frente. Intenta sacar el pecho, apretar el abdomen y tirar con las dorsales para elevarte hacia arriba hasta sobrepasar la barra con la barbilla intentando mantener el resto del cuerpo completamente estático", image="https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg", category="ESPALDA"),
                    Exercise(name="Dominadas Supinas", description="Ejercicio en barra de dominadas para fortalecer la musculatura relacionada con el tirón: dorsales. En menor medida se trabajan los bíceps", image="https://wger.de/media/exercise-images/181/Chin-ups-2.png", category="ESPALDA"),
                    Exercise(name="Elevaciones de rodillas", description="La elevación de piernas a 90° en la barra es un ejercicio muy intenso en el que intervienen todos los músculos abdominales.",   category="ABDOMINALES"),
                    Exercise(name="Elevaciones frontales", description="Para ejecutar el ejercicio, el levantador se para con los pies separados al ancho de los hombros y las pesas o los mangos de resistencia se sostienen a los lados con un agarre en pronación (por encima de la cabeza). El movimiento consiste en llevar los brazos por delante del cuerpo a la altura de los ojos y con sólo una ligera flexión del codo. Esto aísla el músculo deltoides anterior (frente al hombro) y utiliza el deltoides anterior para levantar el peso. Al levantar es importante mantener el cuerpo inmóvil para que el deltoides anterior se utilice por completo; si el peso no se puede levantar estando quieto, entonces es demasiado pesado y se necesita un peso menor. Es importante mantener una ligera flexión en el codo al levantar, ya que mantener el codo trabado agregará tensión a la articulación del codo y podría causar lesiones. También se puede usar un agarre neutral, similar al que se usa en el curl de martillo. Con esta variación, el peso se eleva nuevamente al nivel de los ojos, pero en un ángulo de 45 grados desde la parte frontal del cuerpo. Esto puede ser beneficioso para las personas con lesiones en el hombro, en particular las relacionadas con el manguito de los rotadores.", image="https://wger.de/media/exercise-images/256/b7def5bc-2352-499b-b9e5-fff741003831.png", category="HOMBROS"),
                    Exercise(name="Elevación de pantorrilla derecha", description="<ol><li>Párese en el suelo o en el borde de un escalón para aumentar el rango de movimiento. Levante un pie, colocando la parte superior de su pantorrilla</li><li>Levante los talones hasta que esté de pie</li><li>Manténgase en esta posición durante tres segundos, luego baje el pie sin tocar el suelo con el talón.</li></ol>",   category="PANTORRILLAS"),
                    Exercise(name="Elevación de pantorrilla izquierda", description="<ol><li>Párese en el suelo o en el borde de un escalón para aumentar el rango de movimiento. Levante un pie, colocando la parte superior de su pantorrilla</li><li>Levante los talones hasta que esté de pie</li><li>Manténgase en esta posición durante tres segundos, luego baje el pie sin tocar el suelo con el talón.</li></ol>",   category="PANTORRILLAS"),
                    Exercise(name="Elevación frontal con cable", description="olver a torre de cable, cable entre patas, barra SZ", image="https://wger.de/media/exercise-images/917/068fd666-5460-43e7-aca9-6ba7df74d8ad.png", category="HOMBROS"),
                    Exercise(name="Elevación tibial anterior", description="<ol><li>Pararse derecho</li><li>Levantar la punta de los pies, apoyándose sobre el talón. </li></ol>",   category="PANTORRILLAS"),
                    Exercise(name="Empuje de tríceps en cable", description="El empuje hacia abajo de la cuerda del cable es un ejercicio popular dirigido a los músculos tríceps. Es fácil de aprender y realizar, lo que lo convierte en el favorito de todos, desde principiantes hasta levantadores avanzados. Por lo general, se realiza para repeticiones de moderadas a altas, como 8-12 repeticiones o más por serie, como parte de un entrenamiento centrado en la parte superior del cuerpo o en los brazos.", image="https://wger.de/media/exercise-images/805/ba006cae-44ca-46a9-bb71-6f5d4fa130e9.png", category="BRAZOS"),
                    Exercise(name="Extension de triceps polea", description="Coge el cable, párate con los pies a la altura de los hombros, mantén la espalda recta e inclínate un poco hacia delante. Empuje la barra hacia abajo, asegurándose de que los codos no se muevan durante el ejercicio. Gire las manos hacia afuera al final y vuelva a la posición inicial sin pausa.", image="https://wger.de/media/exercise-images/659/a60452f1-e2ea-43fe-baa6-c1a2208d060c.png", category="BRAZOS"),
                    Exercise(name="Extensión de cuádriceps", description="Es un ejercicio de aislamiento centrado en los cuádriceps, que están formados por cuatro músculos específicos de la parte anterior del muslo: el recto femoral, el vasto lateral, el vasto medio y el vasto intermedio.", image="https://wger.de/media/exercise-images/851/d4b50a4d-cade-4b48-9e6c-7b1a5a822b2a.gif", category="PIERNAS"),
                    Exercise(name="Extensión de triceps", description="Coloque la barra sobre la cabeza con un agarre en pronación estrecho. Baje el antebrazo detrás de la parte superior del brazo con los codos sobre la cabeza. Extienda el antebrazo por encima de la cabeza. Baja y repite.", image="https://wger.de/media/exercise-images/50/695ced5c-9961-4076-add2-cb250d01089e.png", category="BRAZOS"),
                    Exercise(name="Face pull", description="Conecte una cuerda a una estación de polea colocada aproximadamente al nivel del pecho. Da un paso atrás para que estés soportando el peso con los brazos completamente extendidos y asume una postura escalonada (un pie hacia adelante). Doble las rodillas ligeramente para tener una base estable. Retraiga las escápulas (apriete el dedo de su compañero con los omóplatos) y tire del centro de la cuerda ligeramente hacia la cara. Una buena señal es pensar en separar los extremos de la cuerda, no solo en tirar hacia atrás. A medida que se acerca a su cara, gire externamente para que sus nudillos queden mirando hacia el techo. Mantenga durante un segundo en la posición superior y baje lentamente.", image="https://wger.de/media/exercise-images/222/804b4c8c-0b2b-42ed-9d4c-f9321903e10c.png", category="HOMBROS"),
                    Exercise(name="Flexiones a pino", description="Flexiones mientras se hace el pino. Requiere mucha habilidad y fuerza",   category="HOMBROS"),
                    Exercise(name="Flexiones a rotación", description="<ol><li>Haga una flexión de brazos estándar1.a Acuéstese boca abajo1.b Coloque las manos cerca de las orejas1.c Levante el estómago con los brazos hasta que los brazos estén rectos, manteniendo la espalda recta1.d Flexione los brazos hasta que el pecho casi toque el suelo, asegurándose de que la espalda esté recta1.e Levante el estómago de nuevo, volviendo al paso 3</li><li>Gire el cuerpo hacia un lado para que la espalda quede recta, la mano inferior que sostiene el cuerpo esté completamente extendida y sólo las extremidades inferiores toquen el suelo</li><li>Repita, cambiando de lado en el paso 2 otra vez</li></ol>",   category="BRAZOS"),
                    Exercise(name="Flexiones de pica", description="<p>Posición de mirada fija:</p><p>Perro mirando hacia abajo:Tu cuerpo debe hacer una forma de V, con la espalda, los brazos y las piernas rectas. Las caderas deben estar en el aire.Puedes llegar a esta posición caminando con las manos hacia atrás desde una plancha alta.</p><p>Pasos:</p><p>1.Dobla los codos hacia los lados, manteniendo la espalda y las piernas rectas y acercando la cabeza al suelo.</p><ol><li>Estira los brazos, empujando las caderas hacia atrás y manteniendo la espalda y las piernas rectas.</li><li>Repite la operación.</li></ol></li></ol>",   category="BRAZOS"),
                    Exercise(name="Flexión a pino contra la pared", description="Flexiones a pino contra ma pared (pecho cara a la pared). Progresión de las flexiones a pino. Ideal para ganar fuerza en deltoides",   category="HOMBROS"),
                    Exercise(name="Fondos", description="<p>Posición inicial:</p><p>Siéntate con los brazos detrás de ti, apoyando la espalda.Los dedos deben apuntar hacia adelante.Las rodillas deben estar dobladas y los pies juntos.</p><p>Pasos:</p><ol><li>Levanta las caderas del suelo, estirando los brazos.</li><li>Dobla los codos, llevando las caderas hacia abajo.</li><li>Endereza los brazos, volviendo a la posición anterior.</li><li>Repita los pasos 2 y 3.</li></ol><p>Notas:</p><p>La dificultad del ejercicio depende de la altura de las caderas.</p>", image="https://wger.de/media/exercise-images/1000/553266a8-a972-48c5-a014-b12afac66f65.png", category="BRAZOS"),
                    Exercise(name="Fondos en TRX", description="Los fondos se realizan con las manos en cada uno de los agarres de nuestro arnés y despegamos los pies desde el suelo para quedarnos completamente en suspensión. Desde ahí podremos ir haciendo fondos en suspensión exactamente igual que cuando se hacen en anillas o paralelas. Sin embargo, uno de los beneficios que tienen los fondos en TRX es que aumentan la inestabilidad y nos hacen realizar un esfuerzo más intenso.",   category="BRAZOS"),
                    Exercise(name="Hacer Subir", description="Una flexión de brazos es un ejercicio de calistenia que consiste en levantar y bajar el cuerpo con los brazos. Se utilizan comúnmente para desarrollar la fuerza de la parte superior del cuerpo, mejorar la estabilidad central y mejorar la condición física general. Las flexiones se pueden realizar prácticamente en cualquier lugar y no requieren equipo especial, lo que las convierte en un ejercicio conveniente para hacer ejercicio en casa o cuando no tienes acceso a un gimnasio.",   category="PECHO"),
                    Exercise(name="Hindu Pushups", description="Ejercicio para fortalecer los hombros y pectorales. Su nombre se debe a que se empieza en la postura de Yoga 'Perro boca abajo', pasando a 'Cobra' pero sin apoyar las piernas ni torso en el suelo para finalmente acabar con una flexión normal. El ejercicio también se puede realizar hacia atrás (de vuelta a la postura inicial). Como variación, tras hacer la flexión, se puede elevar la cadera para volver a la postura del perro boca abajo", image="https://wger.de/media/exercise-images/1080/c4bf7ba1-6058-4d14-928f-7187885d5d57.webp", category="HOMBROS"),
                    Exercise(name="Inmersiones De Banco En El Piso HD", description="Los fondos de tríceps en el suelo son un ejercicio compuesto, ya que trabajan varios grupos musculares simultáneamente. Aunque este ejercicio de peso corporal se enfoca principalmente en los tríceps, también golpea el pecho y la parte delantera del hombro. Los fondos de tríceps en el suelo son uno de los ejercicios más efectivos para aumentar la fuerza de los brazos y también desarrollar músculo magro en la parte superior de los brazos. Los fondos de tríceps en el suelo son un ejercicio de cadena cinética cerrada y expresan que haces los movimientos alrededor de un punto fijo. Aumenta la fuerza de compresión en las articulaciones, mejorando así la estabilidad.", image="https://wger.de/media/exercise-images/1320/a699df1f-b8a1-4e67-99a3-c25ba410fe3e.gif", category="BRAZOS"),
                    Exercise(name="Jumping Jack HD", description="Los saltos de tijera son un ejercicio pliométrico. Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo. El salto de tijera se enfoca en el brazo, el hombro, los músculos abdominales, los músculos de la cadera y los flexores de la cadera y también trabaja en los muslos, los tendones de la rodilla y los cuádriceps. Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza. Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.", image="https://wger.de/media/exercise-images/1314/554f15e7-31b3-4ea9-86ff-0ebcfca52e0f.gif", category="CARDIO"),
                    Exercise(name="Lagartijas", description="Las flexiones de brazos son un ejercicio en el que una persona, manteniendo una posición boca abajo, con las manos con las palmas hacia abajo bajo los hombros, las puntas de los pies en el suelo y la espalda recta, empuja el cuerpo hacia arriba y lo deja bajar mediante una alternancia de estiramiento y flexión de los brazos.", image="https://wger.de/media/exercise-images/1110/d89c5b93-45df-444b-8735-89db82eec3f5.gif", category="PECHO"),
                    Exercise(name="Levantamiento de piernas", description="<p>Posición inicial:</p><p>Túmbate de espaldas, con los pies juntos y los brazos a los lados.</p><p>Pasos:</p><ol><li>Dobla las rodillas y luego enderézalas para que apunten hacia arriba.</li><li>Manteniendo las piernas rectas, bájalas juntas sin tocar el suelo. Cuanto más bajes, más intenso será el ejercicio.</li><li>Sube las dos piernas juntas hasta que vuelvan a apuntar hacia arriba.</li><li>Repite desde el paso 2.</li></ol>",   category="PIERNAS"),
                    Exercise(name="Media sentadillas derecha", description="<ol><li>Párese con la espalda recta</li><li>De un largo paso adelante con su pierna izquierda</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla derecha</li><li>Suba la pelvis</li><li>Repita desde el paso 3.</li></ol>",   category="PIERNAS"),
                    Exercise(name="Media sentadillas izquierda", description="<ol><li>Párese con la espalda recta</li><li>De un largo paso adelante con su pierna izquierda</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla derecha</li><li>Suba la pelvis</li><li>Repita desde el paso 3.</li></ol>",   category="PIERNAS"),
                    Exercise(name="Montañeros", description="<p>Posición inicial:</p><p>Comienza en la posición de flexión vertical o plancha alta.Las manos deben estar directamente debajo de los hombros.Mantenga la cabeza alineada con la espalda, mirando al suelo.Los pies deben estar separados a la anchura de las caderas.</p><p>Pasos:</p><ol><li>Mueve una rodilla hacia el centro del cuerpo, hacia los codos, manteniendo la otra pierna extendida.</li><li>Con un movimiento rápido de salto, estira la pierna doblada y tira de la otra rodilla hacia tu cuerpo.</li><li>Sigue repitiendo el paso 2, alternando las piernas.</li></ol><p>Notas:</p><p>Durante todo el ejercicio, la espalda debe permanecer lo más recta posible, evitando una joroba o una espalda flácida.</p>",   category="PECHO"),
                    Exercise(name="Oblicuos en TRX", description="1.Place your feet in the stirrups and assume a high plank with your hands directly beneath your shoulders. 2.Pull your knees to your right elbow, then push them back out and to the centre.",   category="ABDOMINALES"),
                    Exercise(name="Patada de rodilla", description="<ol><li>Ponga a cuatro patas</li><li>Empuje un pie hacia atrás hasta que se extienda completamente, concentrándose en los músculos de los glúteos</li><li>Quédese un segundo, y luego vuelva a la posición inicial</li><li>Repita, alternando los pies</li></ol>",   category="PIERNAS"),
                    Exercise(name="Plancha HD", description="Una plancha es un ejercicio isométrico de fuerza central que consiste en mantener una posición similar a una flexión de brazos durante el máximo tiempo posible. Se puede incorporar de manera efectiva en regímenes generales de acondicionamiento físico, programas de entrenamiento atlético de alto rendimiento e incluso protocolos de rehabilitación física.", image="https://wger.de/media/exercise-images/1317/3af4abef-6c4e-4362-b63b-94b4250253ce.gif", category="PECHO"),
                    Exercise(name="Plancha Lateral HD", description="La plancha lateral es un entrenamiento eficaz para fortalecer el tronco. Puede ayudarlo a fortalecer y desarrollar los músculos de la parte superior e inferior del cuerpo. Al ser un movimiento multifuncional, este ejercicio se enfoca no solo en los músculos abdominales, sino también en la columna vertebral y los glúteos. La plancha fortalece y tensa todo el cuerpo, mejora la postura y el equilibrio, reduce la grasa corporal y puede ayudar a acelerar el metabolismo.", image="https://wger.de/media/exercise-images/1321/233fa68d-8a1e-4fc8-b143-377478bdb433.webp", category="ABDOMINALES"),
                    Exercise(name="Plancha a una mano alterna", description="En la posición de plancha correcta, coloque los pies a una distancia ligeramente superior a la anchura de los hombros. Levante y toque alternativamente el hombro opuesto con una mano.", image="https://wger.de/media/exercise-images/1091/50c8912d-54ef-46c9-99d1-633b6196aa1e.jpg", category="ABDOMINALES"),
                    Exercise(name="Plancha de antebrazo", description="<p>Posición de salida:</p><ol><li>Empiece a cuatro patas.Los brazos deben estar doblados en ángulo recto, con los hombros justo sobre los codos.La espalda debe estar recta, todo el cuerpo en línea recta.</li></ol><p>Pasos:</p><ol><li>Mantenga esta posición.</li></ol>", image="https://wger.de/media/exercise-images/458/b7bd9c28-9f1d-4647-bd17-ab6a3adf5770.png", category="ABDOMINALES"),
                    Exercise(name="Plancha de lado derecho", description="<ol><li>Acuéstese sobre su lado correspondiente, con el codo en ángulo recto y el brazo hacia afuera</li><li>Levante la pelvis del suelo levantando el hombro hacia arriba, manteniendo el antebrazo en el suelo; la cabeza, la pelvis y los pies deben estar en línea recta</li><li>Mantenga esta posición</li></ol>",   category="ABDOMINALES"),
                    Exercise(name="Plancha de lado izquierdo", description="<ol><li>Acuéstese sobre su lado correspondiente, con el codo en ángulo recto y el brazo hacia afuera</li><li>Levante la pelvis del suelo levantando el hombro hacia arriba, manteniendo el antebrazo en el suelo; la cabeza, la pelvis y los pies deben estar en línea recta</li><li>Mantenga esta posición</li></ol>",   category="ABDOMINALES"),
                    Exercise(name="Polichilenas", description="<ol><li>Párese con los pies juntos y los brazos a los lados</li><li>Salte a una posición con las piernas abiertas y las manos tocandose por encima de la cabeza</li><li>Repita</li></ol>",   category="PIERNAS"),
                    Exercise(name="Prensa de piernas", description="La prensa de piernas es un ejercicio de entrenamiento con pesas en el que el individuo empuja un peso o una resistencia con las piernas.", image="https://wger.de/media/exercise-images/371/0a7aef34-2f5d-4fcd-b6c6-183fa28765e5.png", category="PIERNAS"),
                    Exercise(name="Prensa de piernas cerrada", description="El ejercicio es muy similar a la prensa de pierna ancha: Siéntese en la máquina y coloque los pies en la plataforma tan separados que podría poner otro pie entre ellos. Los pies son paralelos y apuntan hacia arriba. Baje tanto el peso, que las rodillas formen un ángulo recto. Vuelva a empujar inmediatamente la plataforma hacia arriba, sin ninguna pausa. Cuando está en la posición más baja, las rodillas apuntan un poco hacia afuera y el movimiento debe ser siempre fluido.", image="https://wger.de/media/exercise-images/373/60e2aa21-1910-40d3-9fed-babfee06dd48.png", category="PIERNAS"),
                    Exercise(name="Press Banca Sentado", description="Poner la máquina de press de pecho para que al sentarte los agarres estén alineados con la parte inferior del pecho. Asegúrate de que estás sentado con la espalda bien pegada al asiento. Agarra una manija con cada mano, saca el pecho hacia afuera, mantén la cabeza contra el reposacabezas. Respira profundamente y empuja lentamente las manijas hacia adelante hasta que tus brazos estén casi completamente extendidos. Haz una pausa justo antes del bloqueo, y luego regresa lentamente las manijas a la posición inicial. Haz una pausa justo antes de que las manijas se detengan completamente y realiza otra repetición", image="https://wger.de/media/exercise-images/1094/998ff15d-37af-422f-9936-7d54ac8bdd41.png", category="PECHO"),
                    Exercise(name="Press de banca inclinado", description="Press de banca inclinado con barra fija.", image="https://wger.de/media/exercise-images/41/Incline-bench-press-1.png", category="PECHO"),
                    Exercise(name="Press de piernas abierto", description="Siéntese en la máquina y coloque los pies en la plataforma, un poco más anchos que los hombros. Los pies están girados hacia afuera unos pocos grados. Baje tanto el peso, que las rodillas formen un ángulo recto. Vuelva a empujar inmediatamente la plataforma hacia arriba, sin ninguna pausa. Cuando está en la posición más baja, las rodillas apuntan un poco hacia afuera y el movimiento debe ser siempre fluido.", image="https://wger.de/media/exercise-images/374/dbdb4440-b066-431e-8aea-88e7b1ae9058.png", category="PIERNAS"),
                    Exercise(name="Press de tríceps sentado", description="Siéntese boca arriba (mejor con respaldo). Tome una mancuerna firmemente con ambas manos y sosténgala con los brazos extendidos sobre su cabeza. Con las palmas de las manos hacia arriba y sosteniendo el peso de la mancuerna, baje lentamente el peso detrás de la cabeza.", image="https://wger.de/media/exercise-images/549/765a6343-d28d-4052-86c6-7ae1abdd4992.PNG", category="BRAZOS"),
                    Exercise(name="Press militar", description="En una barra SZ, tome sus manos en el exterior de cada curva y párese con los brazos rectos hacia abajo, con las palmas hacia las piernas. Tire de la barra (doblando los brazos por el codo) hacia el pecho y empuje la barra por encima de la cabeza (los brazos lo más rectos posible). Regrese la barra a su pecho dejando caer los brazos a la altura de los codos. Regrese la barra a su posición original (párese con los brazos hacia abajo, las palmas hacia las piernas).", image="https://wger.de/media/exercise-images/418/fa2a2207-43cb-4dc0-bc2a-039e32544790.png", category="HOMBROS"),
                    Exercise(name="Remo con mancuernas", description="Con las mancuernas en la mano, flexiona la cadera hasta que las manos cuelguen justo por debajo de las rodillas (similar a la posición inicial de pierna recta). Mantenga constante el ángulo de la parte superior del cuerpo mientras contrae los músculos dorsales para llevar los codos hacia atrás, pellizcando los omóplatos en la parte superior. Intenta no levantarte en cada repetición, comprueba que las manos quedan por debajo de las rodillas en cada repetición.", image="https://wger.de/media/exercise-images/81/a751a438-ae2d-4751-8d61-cef0e9292174.png", category="ESPALDA"),
                    Exercise(name="Remo con polea", description="Siéntate, apoya los pies en los puntos de apoyo y agarra la barra con un agarre amplio. Tire de la pesa con un movimiento rápido hacia el ombligo, no hacia arriba. Durante el movimiento, mantén los brazos y los codos pegados al cuerpo. Junta los hombros. Deja que el peso baje lentamente hasta que tus brazos estén completamente estirados.", image="https://wger.de/media/exercise-images/143/Cable-seated-rows-2.png", category="ESPALDA"),
                    Exercise(name="Rodillas elevadas", description="<ol><li>Trote en el lugar, con las rodillas tan altas como pueda y cambie de pierna a un ritmo rápido</li></ol>",   category="CARDIO"),
                    Exercise(name="Saltar la cuerda: saltos básicos", description="<p>Este ejercicio requiere una cuerda para saltar. Asegúrate de que la longitud de la cuerda se ajusta a tu altura. Una forma de comprobarlo es agarrar las dos asas con una mano y situarse en el centro de la cuerda colgando del suelo con un pie. Si la cuerda (excluyendo las asas) te llega justo por debajo del pecho, su longitud es la adecuada. Una cuerda más corta sería peligrosa, ya que podrías golpearte, y una cuerda más larga sería una mala forma.</p><ol><li>Pon los pies juntos, dobla un poco las rodillas, mantén la cabeza y el cuerpo rectos, mantén los codos dentro, abre los brazos.</li><li>Gira sólo las muñecas con la fuerza suficiente para hacer girar la cuerda.</li><li>Salta lo suficiente para pasar la cuerda por debajo de tus pies.</li><li>Repite desde el paso 2.</li></ol>",   category="CARDIO"),
                    Exercise(name="Salto de Tijera HD", description="Los saltos de tijera son un ejercicio pliométrico. Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo. El salto de tijera se enfoca en el brazo, el hombro, los músculos abdominales, los músculos de la cadera y los flexores de la cadera y también trabaja en los muslos, los tendones de la rodilla y los cuádriceps. Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza. Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.", image="https://wger.de/media/exercise-images/1316/5dfe9965-b0f9-4e3d-b590-3bbf2a00ca4c.gif", category="CARDIO"),
                    Exercise(name="Saltos Altos De Rodilla HD", description="Puedes utilizar este ejercicio tanto como calentamiento dinámico antes de entrenar como añadirlo a tu rutina de entrenamiento cardiovascular para quemar grasa. Los saltos altos de rodilla son un ejercicio pliométrico. Los pliométricos son movimientos aeróbicos explosivos que aumentan la velocidad, la rapidez y la potencia y trabajan todo el cuerpo. Los saltos altos de rodilla se dirigen a los oblicuos, los músculos de las piernas, los músculos de la cadera y los flexores de la cadera y también trabajan en los muslos, los tendones de la rodilla, los cuádriceps y los hombros. Los saltos son beneficiosos para la salud porque combinan el acondicionamiento cardiovascular con el trabajo de fuerza. Dado que los saltos elevan el ritmo cardíaco, también pueden mejorar la condición cardiovascular.", image="https://wger.de/media/exercise-images/1318/e62022a4-8a0a-4413-81fb-a6cc1740f6f7.gif", category="CARDIO"),
                    Exercise(name="Sentadilla HD", description="La sentadilla es un tipo de ejercicio de peso corporal. Es uno de los ejercicios más populares para la fuerza y el crecimiento muscular. La sentadilla es particularmente efectiva para enfocarse en los músculos de la pierna y las caderas. Las sentadillas son un ejercicio fácil de hacer para los principiantes. Puede ayudar a fortalecer los músculos de las piernas, tensar los músculos de la cadera y quemar calorías para perder peso. Aprieta los glúteos y las piernas. Las sentadillas son muy efectivas para reafirmar y fortalecer las piernas al actuar sobre los glúteos, los flexores de la cadera, los cuádriceps, los isquiotibiales y los músculos internos del muslo. Además, las sentadillas con peso corporal pueden ayudar a dar forma a los glúteos.", image="https://wger.de/media/exercise-images/1315/ac189cae-1c09-4c62-9e1f-367d7bc6ecf5.gif", category="PIERNAS"),
                    Exercise(name="Sentadilla búlgara derecha", description="<ol><li>Póngase de pie delante de una silla y dé un largo paso. Ponga la parte superior de uno de sus pies en la silla</li><li>Doble la rodilla delantera, balanceando los brazos hasta que la rodilla trasera casi toque el suelo.</li><li>Empuje hacia atrás a la posición inicial y repita.</li></ol>", image="https://wger.de/media/exercise-images/989/2cf38717-db42-4df7-bfc1-83c8354fb786.png", category="PIERNAS"),
                    Exercise(name="Sentadilla búlgara izquierda", description="<ol><li>Póngase de pie delante de una silla y dé un largo paso. Ponga la parte superior de uno de sus pies en la silla</li><li>Doble la rodilla delantera, balanceando los brazos hasta que la rodilla trasera casi toque el suelo.</li><li>Empuje hacia atrás a la posición inicial y repita.</li></ol>", image="https://wger.de/media/exercise-images/988/6283b258-a4d7-4833-84f7-a38987022d3d.png", category="PIERNAS"),
                    Exercise(name="Sentadilla de lado derecho", description="<ol><li>Póngase de pie y dé un amplio paso lateral, un poco más grande que el ancho de los hombros</li><li>Doble una rodilla hasta que su muslo esté paralelo al suelo. La rodilla doblada debe estar en línea con el pie</li><li>Vuelva a la posición inicial y repita.</li></ol>",   category="PIERNAS"),
                    Exercise(name="Sentadilla de lado izquierdo", description="<ol><li>Póngase de pie y dé un amplio paso lateral, un poco más grande que el ancho de los hombros</li><li>Doble una rodilla hasta que su muslo esté paralelo al suelo. La rodilla doblada debe estar en línea con el pie</li><li>Vuelva a la posición inicial y repita.</li></ol>",   category="PIERNAS"),
                    Exercise(name="Sentadillas", description="La sentadilla es un tipo de ejercicio de peso corporal. Es uno de los ejercicios más populares para la fuerza y el crecimiento muscular. La sentadilla es particularmente efectiva para concentrarse en los músculos de la pierna y la cadera. Las sentadillas son un ejercicio fácil de hacer para principiantes. Puede ayudar a fortalecer los músculos de las piernas, tensar los músculos de la cadera y quemar calorías para perder peso. Tensa el trasero y las piernas. Las sentadillas son muy efectivas para reafirmar y fortalecer las piernas actuando sobre los glúteos, flexores de la cadera, cuádriceps, isquiotibiales y músculos internos del muslo. Además, las sentadillas con peso corporal pueden ayudar a moldear los glúteos y las nalgas.",   category="PIERNAS"),
                    Exercise(name="Sentadillas en pistol derecha", description="<ol><li>Párese en una pierna, con la otra pierna estirada y ligeramente hacia adelante.</li><li>Doble una rodilla lentamente, bajando en sentadilla y manteniendo la espalda y la otra pierna estirada.</li><li>Levántese lentamente de la sentadilla, enderezando la rodilla doblada y manteniendo la otra pierna recta.</li><li>Repita</li></ol>",   category="PIERNAS"),
                    Exercise(name="Sentadillas en pistol izquierda", description="<ol><li>Párese en una pierna, con la otra pierna estirada y ligeramente hacia adelante.</li><li>Doble una rodilla lentamente, bajando en sentadilla y manteniendo la espalda y la otra pierna estirada.</li><li>Levántese lentamente de la sentadilla, enderezando la rodilla doblada y manteniendo la otra pierna recta.</li><li>Repita</li></ol>", image="https://wger.de/media/exercise-images/456/3b681e59-377b-40db-9113-ca5873ce084b.jpg", category="PIERNAS"),
                    Exercise(name="Squat con barra", description="Controla la bajada, baja en 2 segundos y sube lo más explosivo que puedas. Es muy importante que hagas movilidad de cadera antes de empezar a entrenar, para mejorar la profundidad. Olvidate del peso, baja todo lo que puedas, sin levantar los talones del suelo y sube par arriba. Una buena técnica va a generarte más hipertrofia que mucho peso sin un ROM correcto.", image="https://wger.de/media/exercise-images/849/783d980c-af07-4ac0-a525-6dc8c426a204.gif", category="PIERNAS"),
                    Exercise(name="Subida a peldaño", description="<ol><li>Párese frente a una silla</li><li>Súbase a la silla</li><li>Bájese de la silla</li><li>Repita</li></ol>",   category="PIERNAS"),
                    Exercise(name="TRX - curl de bíceps a un brazo", description="colocar las cintas cruzadas, para dejar toda la fuerza en una sola cuerda y que sea más seguro el ejercicio. Para su realización nos vamos a colocar inclinados lateralmente. El brazo con el que vamos a trabajar será el que agarre la cinta del TRX que hemos montado combinando los dos agarres. El otro brazo lo dejaremos relajado lateralmente, ya que no actuará en este momento, pues sólo entrará en acción la parte del bíceps del brazo que tenemos agarrado a la cinta. El cuerpo, al igual que anteriormente, permanecerá recto, mirando al frente y cuanto más nos inclinemos mayor será la resistencia que tengamos que vencer durante el ejercicio. Ambas piernas, en este caso, estarán juntas para solamente mantener el brazo estirado para doblarlo por el codo. Este movimiento activará el bíceps y con ello trabajaremos esta parte del brazo.",   category="BRAZOS"),
                    Exercise(name="TRX- biceps gorila", description="Nos colocaremos de frente a las cintas del TRX y las agarraremos con los puños de las manos enfrentados y al frente, con los brazos totalmente estirados a la altura más o menos de los hombros. El cuerpo lo mantendremos recto hacia atrás, como en los anteriores ejercicios, ya que lo que vamos a hacer es mediante la activación de los bíceps, elevar el cuerpo hacia las cintas del TRX. El cuerpo estará recto y los pies apoyados en el suelo. Los brazos en esta ocasión, los vamos a colocar abiertos hacia los lados, y a la altura del pecho. El movimiento que vamos a hacer será una contracción hacia el pecho. Para conseguirlo, lo que haremos será doblar los codos para que, mediante la activación de los bíceps atraigamos el cuerpo hacia las cintas.",   category="BRAZOS"),
                    Exercise(name="Tirar de cables sentados", description="Manténgase inclinado hacia adelante, meta los codos en el lado negativo", image="https://wger.de/media/exercise-images/921/2555c4c3-a84d-47db-b83b-cbf721f12e45.png", category="ESPALDA"),
                    Exercise(name="Zancadas con peso", description="<ol><li>Párese con la espalda recta</li><li>Dé un gran paso adelante con su pierna izquierda</li><li>Baje la pelvis hasta que casi toque el suelo con la rodilla derecha</li><li>Vuelva a subir la pelvis</li><li>Vuelva a la posición con el pie hacia atrás</li><li>Repita, cambiando de pierna cada vez</li></ol>", image="https://wger.de/media/exercise-images/984/5c7ffe68-e7b2-47f3-a22a-f9cc28640432.png", category="PIERNAS"),
                    Exercise(name="extensiones de triceps con trx", description="POSICIÓN INICIAL: Suspenda su TRX a la altura de la rodilla. Agarre las asas con un agarre prono y coloque sus piernas juntas detrás de usted. Su posición debe verse como una posición de push up. Mantenga su cuerpo en línea recta y sus brazos completamente extendidos retrayendo los omóplatos. Contraiga el suelo pelvico y el core mientras mantiene su cuerpo recto. Mueva sus manos para colocarlas juntas. Las cuerdas del TRX deben estar justo por encima de su cabeza y que deberían tener tensión. EJECUCIÓN: Comience a bajar doblando los codos hasta que las manos toquen la frente mientras inhala. No separe los codos entre ellos. Asegúrese de sólo mover los codos cuando realice el ejercicio. Empuje su torso hacia la posición inicial apretando el resto del cuerpo mientras exhala. Asegúrese de que sus escápulas siempre están retraídas.",   category="BRAZOS"),
                    Exercise(name="flexiones en TRX", description="Las&nbsp;flexiones de brazos&nbsp;en TRX añaden un componente de inestabilidad que hará que tus&nbsp;hombros y tus pectorales trabajen de manera diferente. Puedes hacer que el ejercicio sea más o menos intenso colocando tu cuerpo más paralelo o menos al suelo. Evita que tus brazos rocen con las cuerdas porque puede que no lo notes mientras entrenas, pero podrás tener rozaduras y moratones después.", image="https://wger.de/media/exercise-images/927/7b392101-9c47-4693-935e-a88b1887eec5.jpg", category="CARDIO"),
                ]
                db.session.add_all(exercises)

                db.session.commit()
                print(f"DB poblada con exito")
        except Exception as e:
            print(f"Error al poblar la DB: {e}")