import React from "react";
const Terms = () => {
  return (
    <div
    className="container"
      style={{
        backgroundColor: "rgba(231, 231, 231)",
        marginBottom: "20px",
        paddingLeft: "50px",
      }}>
      <h3 class="text-center">Terminos y Condiciones</h3>
      <p className="text-black">Al leer los Términos y Condiciones conocemos las reglas de uso y las cláusulas legales que establecen la forma en la que puedes usar la información y acceder a los contenidos.</p>
      <div class="accordion" id="accordionPanelsStayOpenExample">
  <div className="accordion-item">
    <h2 className="accordion-header" id="panelsStayOpen-headingOne">
      <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        Dueño de Mascota
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" className="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div className="accordion-body">
      <strong>Terminos de Servicio. </strong>
      Los Servicios incluyen una plataforma tecnológica de mercado que conecta a los Proveedores de Cuidado de Mascotas con los Propietarios de Mascotas. No proporcionamos ningún servicio de cuidado de mascotas y no hacemos ninguna representación o garantía sobre la calidad de los paseos de mascotas, embarcaciones, transporte u otros servicios proporcionados por los Proveedores de Cuidado de Mascotas, o sobre sus interacciones y tratos con los Proveedores de Cuidado de Mascotas u otros usuarios. Dogger! no emplea, recomienda ni avala a los propietarios de mascotas ni a los proveedores de cuidados de mascotas, y no somos responsables del rendimiento o la conducta de los propietarios de mascotas o de los proveedores de cuidados de mascotas, ya sea en línea o fuera de ella. Dogger! no consigue un seguro para los propietarios de mascotas (o sus mascotas) o los cuidadores de mascotas, ni es responsable de la propiedad de los propietarios de mascotas o de los cuidadores de mascotas.
Dogger! proporciona a los cuidadores de mascotas acceso a proveedores externos que realizan comprobaciones de antecedentes y verificaciones. Dogger! no realiza comprobaciones de antecedentes y no verifica de forma independiente la información de las comprobaciones de antecedentes. Dogger! no es responsable de ninguna manera de las verificaciones de antecedentes.
7. Condiciones de pago para los propietarios de mascotas.
7.1 Condiciones generales de pago.
Como propietario de una mascota, usted entiende que el uso de los Servicios puede dar lugar a que usted deba pagar al Proveedor de Cuidados de Mascotas por los servicios de cuidado de mascotas que reciba de dicho Proveedor de Cuidados de Mascotas. Dogger! le facilitará el pago de los cargos aplicables en nombre del Proveedor de Cuidados de Mascotas a través de procesadores de pago de terceros, con los que deberá establecer una cuenta para acceder a los Servicios.  El pago de dichos cargos de esta manera se considerará igual que el pago realizado directamente por usted al Proveedor de Servicios para Mascotas. Los cargos incluirán los impuestos aplicables cuando así lo exija la ley. Los cargos pagados por el usuario son definitivos y no son reembolsables, independientemente de su decisión de terminar el uso de los Servicios, de la decisión de Dogger! de terminar su uso, de cualquier interrupción de los Servicios, o de cualquier otra razón, a menos que Dogger! determine lo contrario.
Todos los cargos deben ser pagados inmediatamente y Dogger!, o un procesador de pagos de terceros, procesará su pago en nombre del Proveedor de Cuidados de Mascotas utilizando el método de pago principal designado por usted en su cuenta de Dogger! Si se determina que su método de pago primario está caducado, no es válido o no se puede cobrar de otra manera, usted acepta que Dogger! puede, como agente de cobro limitado del Proveedor de Servicios para Mascotas, utilizar un método de pago secundario en su cuenta, si está disponible.
Los propietarios de mascotas y los proveedores de cuidados de mascotas realizan transacciones entre sí en la plataforma tecnológica del mercado de Dogger! cuando ambos acuerdan una "reserva" que especifica los honorarios, el período de tiempo, la política de cancelación y otros términos para la prestación de servicios de cuidado de mascotas a través del mecanismo de reserva.
Los propietarios de mascotas y los proveedores de cuidados de mascotas realizan transacciones entre sí en la plataforma tecnológica del mercado de Dogger! cuando ambos acuerdan una "reserva" que especifica los honorarios, el período de tiempo, la política de cancelación y otros términos para la prestación de servicios de cuidados de mascotas a través del mecanismo de reserva proporcionado en la plataforma tecnológica del mercado de Dogger! Usted puede elegir realizar transacciones con determinados Proveedores de Cuidado de Mascotas de vez en cuando en base a una variedad de factores a su discreción, como su rango de precios deseado, la tarifa de precios de los servicios para mascotas de un Proveedor de Cuidado de Mascotas, el perfil de un Proveedor de Cuidado de Mascotas y las calificaciones y reseñas de estrellas de un Proveedor de Cuidado de Mascotas. Una vez que solicite un servicio de cuidado de mascotas, usted se compromete a pagar al Proveedor de Cuidado de Mascotas el precio acordado y a cumplir con los demás términos de dicha reserva. Usted puede optar por cancelar su solicitud de servicios de un Proveedor de cuidados de mascotas en cualquier momento antes de la llegada de dicho Proveedor de cuidados de mascotas, en cuyo caso puede estar sujeto a una tasa de cancelación.
Los honorarios debidos a los Proveedores de Cuidados de Mascotas no incluyen la propina o gratificación para el Proveedor de Cuidados de Mascotas. Aunque usted es libre de dar una propina a cualquier Proveedor de Cuidados de Mascotas que le preste servicios obtenidos a través de los Servicios, no tiene ninguna obligación de hacerlo. Una vez que haya recibido los servicios o bienes obtenidos a través de los Servicios, tendrá la oportunidad de calificar su experiencia y dejar comentarios adicionales sobre su Proveedor de Cuidados de Mascotas.
Además de las tarifas anteriores, usted entiende y reconoce que puede incurrir en cargos auxiliares en relación con su recepción de servicios de cuidado de mascotas de los Proveedores de Cuidado de Mascotas ("Cargos"). Dichos Cargos pueden incluir alguna combinación de lo siguiente: (1) tasa de cancelación, (2) tasa de servicio, reserva o uso de la plataforma, (3) tasa de confianza y seguridad, (4) recargos, (5) tasa de conveniencia y (6) otras tasas. La descripción de cualquier cargo estará disponible en los Servicios. Usted tiene absoluta discreción para solicitar o no los servicios de un Proveedor de Cuidados de Mascotas si la tarifa o cargo total aplicable no es aceptable para usted.
De vez en cuando, Dogger! puede, a su entera discreción, poner a disposición de los Propietarios de Mascotas ciertas promociones, ofertas, créditos, recompensas, suscripciones o enlaces o códigos de referencia (las "Promociones"). ¡Dichas promociones se proporcionarán a los propietarios de mascotas a través de los Servicios, por correo electrónico, o se pondrán a disposición de forma electrónica por Dogger! Dichas Promociones sólo son válidas para ser canjeadas a través de los Servicios y no son transferibles ni canjeables por dinero en efectivo, salvo en los casos en que la ley lo exija. Cada promoción es una oferta de tiempo limitado y es válida sólo para el tiempo y el propósito y bajo los términos y condiciones especificados en el mismo, que puede incluir requisitos de elegibilidad, tiempo y ubicación. Dogger!, a su entera discreción, se reserva el derecho de emitir Promociones con diferentes características, descuentos, ofertas o tratos a cualquier usuario o grupo de usuarios que Dogger! determine exclusivamente. Dichas Promociones, salvo que se realicen para ti, no tendrán relación alguna con el uso que hagas de los Servicios o de las Promociones que se te ofrezcan. Dogger! se reserva el derecho de retener o deducir los créditos u otras características o beneficios obtenidos a través del uso de las Promociones que se hayan realizado por error o que se hayan obtenido a través de un fraude o de una presunta conducta ilegal, o cuando se haya comprobado que el Propietario de la Mascota ha violado los términos de dicha Promoción, estos Términos, o los Términos Adicionales. Las promociones pueden ser modificadas, deshabilitadas o retiradas por Dogger! en cualquier momento, por cualquier razón o sin razón, sin responsabilidad para Dogger!
Reconoces y aceptas que Dogger! puede limitar o suspender temporal o permanentemente tu uso o acceso a los Servicios si (1) has proporcionado información inexacta, fraudulenta, obsoleta o incompleta en relación con un método de pago, (2) cualquier cantidad que debas por los servicios de cuidado de mascotas está atrasada o en mora, o (3) Dogger! cree de buena fe que dicha acción es razonablemente necesaria para proteger la seguridad personal o la propiedad de Dogger!, nuestros usuarios, cualquier procesador de pagos de terceros o terceros, o para prevenir el fraude u otra actividad ilegal.
7.2 Renovación y cancelación automática de la suscripción.
      </div>
    </div>
  </div>
  <div className="accordion-item">
    <h2 className="accordion-header" id="panelsStayOpen-headingTwo">
      <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        Caminador
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" className="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div className="accordion-body">
      <strong>Terminos de Servicio. </strong>
      ¡El servicio de mensajes de texto Dogger! ¡Updates for Pet Care Providers (el "Servicio") es operado por Dogger! Labs, Inc. ("Dogger!", "nosotros", o "nos").  El uso del Servicio constituye su acuerdo con estos términos y condiciones ("Términos móviles").  ¡Las Condiciones de Servicio de Dogger! (incluyendo un acuerdo de arbitraje mutuo) y la Política de Privacidad también se aplican a su uso del Servicio. Podemos modificar o cancelar el Servicio o cualquiera de sus características sin previo aviso. También podemos modificar estas Condiciones de uso del móvil en cualquier momento y su uso continuado del Servicio tras la fecha de entrada en vigor de dichos cambios constituirá su aceptación de los mismos.
Dogger! no cobra por el Servicio, pero el usuario es responsable de todos los cargos y tasas asociados a la mensajería de texto impuestos por su proveedor de telefonía móvil. Pueden aplicarse tarifas de mensajes y datos. Los mensajes de texto pueden ser enviados utilizando un sistema de marcación telefónica automática u otra tecnología. Su consentimiento para recibir mensajes de texto de marketing de marcación automática no es necesario como condición para la compra de ningún bien o servicio. ¡Si ha optado por ello, el Servicio proporciona actualizaciones de servicios, alertas, información, promociones, ofertas especiales y otras ofertas de marketing de Dogger! Pet Care Providers a través de mensajes de texto a través de su proveedor de telefonía móvil al número de móvil que usted proporcionó. El Servicio es un programa de mensajes recurrentes. La frecuencia de los mensajes varía. Puede recibir varios mensajes al mes. Envíe un mensaje de texto con la palabra clave STOP al 24006 para cancelar el servicio en cualquier momento. Recibirá un único mensaje de texto de confirmación de cancelación. Si te has suscrito a otros programas de mensajes móviles de Dogger! y deseas cancelarlos, deberás cancelar tu suscripción por separado de esos programas siguiendo las instrucciones proporcionadas en sus respectivos términos móviles. Para obtener ayuda o asistencia del Servicio, envíe un mensaje de texto con el texto HELP al 24006, o llame a nuestro equipo de éxito del cliente al (628) 400-4426 o al (855) 732-9513, o envíenos un correo electrónico a Support@dogger.com.
El usuario reconoce que cualquier mensaje, incluyendo cualquier solicitud de PARADA o AYUDA, que envíe a un código corto o número de teléfono que hayamos cambiado puede no ser recibido y Dogger! no será responsable de atender las solicitudes realizadas en dichos mensajes.
Los proveedores de servicios inalámbricos compatibles con el Servicio no son responsables de los mensajes retrasados o no entregados. Usted se compromete a proporcionarnos un número de móvil válido. Si cambia su número de teléfono móvil, acepta darse de baja del Servicio antes de cambiar su número de móvil.
Usted acepta indemnizarnos, defendernos y eximirnos de cualquier reclamación, responsabilidad, daño o coste de terceros que se derive de su uso del Servicio o de que nos proporcione un número de teléfono que no sea el suyo.
Usted acepta que no seremos responsables de la entrega fallida, retrasada o mal dirigida de cualquier información enviada a través del Servicio; de cualquier error en dicha información; y/o de cualquier acción que usted pueda o no tomar basándose en la información o el Servicio.
      </div>
    </div>
  </div>
  <hr/>
</div>
    </div>
  );
};
export default Terms;